/*
 * tests/blob_guard_host_test.c -- the embedded-child blob guard.
 *
 * user/examples/cap_recycle_child_blob.h is a GENERATED artifact: the
 * Makefile re-extracts cap_recycle_child.bin into it on every
 * "make user-programs" (see the rule in the Makefile). That rule makes the
 * normal flow self-healing, but it is driven purely by file timestamps:
 * a HAND-EDIT of the header makes it newer than its prerequisite, so make
 * considers it up to date, regenerates nothing, and the embedded child
 * silently drifts from the binary part_recycle.c actually uploads. A
 * broken regeneration pipeline would be just as invisible -- the rule would
 * "succeed" and produce wrong bytes.
 *
 * This guard is the CI-style backstop for both failure modes: it ignores
 * timestamps entirely, re-extracts CAP_RECYCLE_CHILD_BLOB out of the
 * header, and asserts it matches cap_recycle_child.bin byte-for-byte (and
 * that CAP_RECYCLE_CHILD_BLOB_LEN equals the array's actual byte count).
 * It is auto-discovered by tests/run_all.sh (the tests glob over the
 * *_host_test.c files) and therefore runs in CI's "Host test suite" step.
 *
 * On a fresh clone cap_recycle_child.bin does not exist (gitignored build
 * artifact). run_all.sh builds the user programs before the loop -- same
 * rule as the SIMI corpus it already assembles -- and, like
 * simi_interp_host_test.c, a missing binary here is a FAILURE, not a skip:
 * an embedded child that cannot be compared against its source binary has
 * not been checked.
 *
 * Build and run:
 *   gcc -std=c11 -Wall -Wextra -o /tmp/blob_guard_host_test \
 *       tests/blob_guard_host_test.c
 *   /tmp/blob_guard_host_test
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define BLOB_MAX 4096

static unsigned char g_blob[BLOB_MAX];
static size_t        g_blob_len = 0;
static unsigned long g_defined_len = 0;

/* Parse CAP_RECYCLE_CHILD_BLOB and CAP_RECYCLE_CHILD_BLOB_LEN out of the
 * generated header. Returns 0 on success, nonzero with a printed reason on
 * any structural problem. */
static int parse_header(const char *path)
{
    FILE *f = fopen(path, "r");
    if (!f) {
        printf("FAIL: cannot open %s\n", path);
        return -1;
    }

    char line[1024];
    int  in_array = 0;
    int  found_array = 0;
    int  have_defined = 0;
    while (fgets(line, sizeof line, f)) {
        if (strstr(line, "#define CAP_RECYCLE_CHILD_BLOB_LEN")) {
            const char *p = strstr(line, "CAP_RECYCLE_CHILD_BLOB_LEN");
            p += strlen("CAP_RECYCLE_CHILD_BLOB_LEN");
            g_defined_len = strtoul(p, NULL, 10);
            have_defined = 1;
            continue;
        }
        if (!in_array) {
            if (strstr(line, "CAP_RECYCLE_CHILD_BLOB[]")) {
                in_array = 1;
                found_array = 1;
            }
            continue;
        }
        if (strstr(line, "};")) {
            in_array = 0;   /* keep scanning: the LEN define follows the array */
            continue;
        }
        for (const char *q = line; (q = strstr(q, "0x")) != NULL; q += 2) {
            if (g_blob_len >= BLOB_MAX) {
                printf("FAIL: CAP_RECYCLE_CHILD_BLOB exceeds %d bytes in %s\n",
                       BLOB_MAX, path);
                fclose(f);
                return -1;
            }
            g_blob[g_blob_len++] = (unsigned char)strtoul(q, NULL, 16);
        }
    }
    fclose(f);

    if (!found_array) {
        printf("FAIL: CAP_RECYCLE_CHILD_BLOB array not found in %s -- is it\n"
               "      still generated by the Makefile rule?\n", path);
        return -1;
    }
    if (!have_defined) {
        printf("FAIL: CAP_RECYCLE_CHILD_BLOB_LEN not found in %s\n", path);
        return -1;
    }
    return 0;
}

int main(void)
{
    const char *hdr = "user/examples/cap_recycle_child_blob.h";
    const char *bin = "user/examples/cap_recycle_child.bin";
    int  fails = 0;

    if (parse_header(hdr) != 0) {
        fails++;
    } else {
        printf("ok: parsed CAP_RECYCLE_CHILD_BLOB (%zu bytes) and "
               "CAP_RECYCLE_CHILD_BLOB_LEN (%lu) from %s\n",
               g_blob_len, g_defined_len, hdr);

        if (g_defined_len != g_blob_len) {
            printf("FAIL: CAP_RECYCLE_CHILD_BLOB_LEN says %lu but the array "
                   "holds %zu bytes\n", g_defined_len, g_blob_len);
            fails++;
        } else {
            printf("ok: CAP_RECYCLE_CHILD_BLOB_LEN matches the array's "
                   "actual byte count\n");
        }

        FILE *f = fopen(bin, "rb");
        if (!f) {
            printf("FAIL: cannot open %s -- run 'make user-programs' first\n",
                   bin);
            fails++;
        } else {
            unsigned char binbuf[BLOB_MAX];
            size_t n = fread(binbuf, 1, sizeof binbuf, f);
            fclose(f);
            printf("ok: read %s (%zu bytes)\n", bin, n);

            if (n != g_blob_len) {
                printf("FAIL: %s is %zu bytes but the header blob is %zu "
                       "bytes\n", bin, n, g_blob_len);
                fails++;
            } else if (memcmp(binbuf, g_blob, n) != 0) {
                size_t i;
                for (i = 0; i < n; i++)
                    if (binbuf[i] != g_blob[i])
                        break;
                printf("FAIL: header blob diverges from %s at byte %zu "
                       "(0x%02x vs 0x%02x) -- regenerate with "
                       "'make user-programs'\n",
                       bin, i, binbuf[i], g_blob[i]);
                fails++;
            } else {
                printf("ok: header blob matches %s byte-for-byte "
                       "(%zu bytes)\n", bin, n);
            }
        }
    }

    if (fails) {
        printf("FAILED: %d check(s) -- the embedded child has drifted from "
               "its binary; run 'make user-programs' and re-check\n", fails);
        return 1;
    }
    printf("ALL PASS: embedded child matches its binary\n");
    return 0;
}
