/*
 * simi_interp_host_test.c — verification for kernel/simi_interp.c, the
 * in-kernel SIMI interpreter that makes Persistent Execution Contexts
 * possible. Links the REAL, unmodified kernel/simi_interp.c.
 *
 * ─── What this has to prove, and why ─────────────────────────────────
 * Two independent things, and they fail in completely different ways:
 *
 *   1. CORRECTNESS — the port computes what the reference computes. The
 *      SIMI project already cross-validates three implementations (the
 *      host reference interpreter, the x86 JIT, the RV64 backend) against
 *      a shared corpus; a fourth that quietly disagrees would break that
 *      guarantee silently, and translated-vs-interpreted execution of the
 *      SAME program would diverge. Scenario 1 runs the real corpus and
 *      compares against the reference's own recorded expected values.
 *
 *   2. RESUMABILITY — running a program in N budget-limited slices must
 *      give bit-identical results to running it in one. This is the
 *      property Persistent Execution Contexts are built on: if state is
 *      complete at an instruction boundary, slicing is invisible. If any
 *      execution state lives outside struct SimiContext, slicing exposes
 *      it. Scenario 2 slices at every budget from 1 upward, which is the
 *      strongest form of that check available -- a bug that only appears
 *      when a slice boundary lands on a CALL or a taken branch is exactly
 *      the kind a handful of arbitrary budgets would miss.
 *
 * Build and run:
 *   gcc -Wall -Wextra -std=c11 -I . -I kernel -I drivers -I tools/simi \
 *       -o /tmp/simi_interp_host_test \
 *       tests/simi_interp_host_test.c kernel/simi_interp.c tools/simi/simi_obj.c
 *   /tmp/simi_interp_host_test
 */
/* Include the AUTHORITATIVE ISA header FIRST. kernel/simi_interp.h then
 * skips its mirrored copy (it guards on SIMI_ISA_H), so this TU sees the
 * real definitions -- and simi_interp_isa_fingerprint(), compiled in the
 * OTHER TU against the mirrored copy, can be compared against them. That
 * cross-TU comparison is what catches drift. */
#include "tools/simi/simi_isa.h"
#include "tools/simi/simi_obj.h"
#include "kernel/simi_interp.h"

#include <stdio.h>
#include <string.h>
#include <stdint.h>

static int checks_passed = 0;
static int checks_failed = 0;
#define CHECK(cond, msg) do { \
    if (!(cond)) { printf("FAIL: %s\n", msg); checks_failed++; } \
    else         { printf("ok:   %s\n", msg); checks_passed++; } \
} while (0)

/* ─── Catalog bindings ───────────────────────────────────────────────
 * kernel/simi_interp.c calls the REAL simi_rt_* (kernel/simi_runtime.c),
 * which walks object_catalog[]. Linking that here would drag in the whole
 * catalog subsystem, so these fakes mirror the reference interpreter's own
 * mock table EXACTLY -- same names, same base_vaddrs, same sizes, same
 * types. That is what makes corpus programs using RESOLVE/OBJSIZE/OBJTYPE
 * comparable against the reference's recorded output at all. */
#define MOCK_OBJ_TYPE_PROGRAM 1
#define MOCK_OBJ_TYPE_DATA    2
static const struct { const char* name; uint64_t base; uint32_t size; uint32_t type; }
g_mock[] = {
    { "simi_add_test2", 0x2000, 303, MOCK_OBJ_TYPE_PROGRAM },
    { "simi_verify3",   0x3000, 100, MOCK_OBJ_TYPE_DATA    },
};
#define MOCK_N (sizeof(g_mock)/sizeof(g_mock[0]))

uint64_t simi_rt_resolve(const char* name) {
    for (size_t i = 0; i < MOCK_N; i++)
        if (strcmp(g_mock[i].name, name) == 0) return g_mock[i].base;
    return 0;
}
uint64_t simi_rt_objsize(uint64_t v) {
    for (size_t i = 0; i < MOCK_N; i++) if (g_mock[i].base == v) return g_mock[i].size;
    return 0;
}
uint64_t simi_rt_objtype(uint64_t v) {
    for (size_t i = 0; i < MOCK_N; i++) if (g_mock[i].base == v) return g_mock[i].type;
    return 0xFFFFFFFFu;
}
void kernel_serial_print(const char* s) { (void)s; }
void kernel_serial_printf(const char* fmt, ...) { (void)fmt; }

/* ─── Corpus ─────────────────────────────────────────────────────────
 * The complete tools/simi/tests corpus: 16 integer programs plus the one
 * float program, which must be refused rather than approximated. Programs
 * out of this interpreter's v1 scope carry the status they should trap
 * with instead of a result. */
struct Case {
    const char* file;
    const char* entry;
    int         expect_halt;      /* 1 = should HALT with `result` */
    int64_t     result;
    SimiStatus  expect_status;    /* checked when expect_halt == 0 */
};

static struct Case cases[] = {
    /* Expected values were GENERATED by running the reference interpreter
     * (tools/simi/simi-run) over the whole corpus, not transcribed from
     * source comments by hand. That distinction earned itself immediately:
     * the first hand-written version of this table had branch_cmp's
     * expected value as 1 when the reference says 99, which showed up as a
     * "port is wrong" failure that was actually a wrong test. */
    { "tools/simi/tests/add.tmo", "main", 1, 5LL, SIMI_STATUS_OK },
    { "tools/simi/tests/aggregate_abi.tmo", "main", 1, 142LL, SIMI_STATUS_OK },
    { "tools/simi/tests/branch_cmp.tmo", "main", 1, 99LL, SIMI_STATUS_OK },
    { "tools/simi/tests/call_ret.tmo", "main", 1, 42LL, SIMI_STATUS_OK },
    { "tools/simi/tests/cap_call_ret.tmo", "main", 1, 2100303LL, SIMI_STATUS_OK },
    { "tools/simi/tests/cap_forge.tmo", "main", 1, 3000304LL, SIMI_STATUS_OK },
    { "tools/simi/tests/extra_ops.tmo", "main", 1, -15LL, SIMI_STATUS_OK },
    { "tools/simi/tests/jmpr_basic.tmo", "main", 1, 222LL, SIMI_STATUS_OK },
    { "tools/simi/tests/loadi64.tmo", "main", 1, 10000000001LL, SIMI_STATUS_OK },
    { "tools/simi/tests/loop_sum.tmo", "main", 1, 55LL, SIMI_STATUS_OK },
    { "tools/simi/tests/mem_ops.tmo", "main", 1, 6912LL, SIMI_STATUS_OK },
    { "tools/simi/tests/mem_ops_native.tmo", "main", 1, 6912LL, SIMI_STATUS_OK },
    { "tools/simi/tests/obj_ops.tmo", "main", 1, 305LL, SIMI_STATUS_OK },
    { "tools/simi/tests/ptr_ops.tmo", "main", 1, 125LL, SIMI_STATUS_OK },
    { "tools/simi/tests/rv64_boot_smoke.tmo", "main", 1, 42LL, SIMI_STATUS_OK },
    { "tools/simi/tests/straight_line_bench.tmo", "main", 1, 21LL, SIMI_STATUS_OK },
    /* ─── Phase 15 atomics ─────────────────────────────────────────────────
     * OP_CAS and OP_ATOMIC_ADD reached the ISA and all three code generators
     * with NO interpreter coverage at all: the .simi sources existed here, but
     * none was in this corpus, so the kernel interpreter had never executed
     * either opcode. The ISA drift guard above caught that the enum was
     * missing; nothing would have caught the semantics being wrong.
     *
     * Expected values are the reference interpreter's (tools/simi/simi-run),
     * cross-checked against each program's own documented "Expected result".
     * That matters more here than elsewhere in this list: the kernel and host
     * interpreters are separate implementations of the same ISA, not copies,
     * so these three are the only thing making them agree about atomics. */
    { "tools/simi/tests/atomic_add.tmo",     "main", 1, 2LL, SIMI_STATUS_OK },
    { "tools/simi/tests/cas_simple.tmo",     "main", 1, 5LL, SIMI_STATUS_OK },
    { "tools/simi/tests/stress_atomics.tmo", "main", 1, 0LL, SIMI_STATUS_OK },
    /* The one float program must be REFUSED, not approximated -- see
     * simi_interp.h on -mno-sse and x87's 80-bit intermediates. Asserting
     * the refusal means a future change that starts computing floats
     * slightly differently fails here instead of passing quietly. */
    { "tools/simi/tests/float_ops.tmo", "main", 0, 0, SIMI_STATUS_TRAP_FLOAT_UNSUPPORTED },
};
#define NCASES (sizeof(cases)/sizeof(cases[0]))

/* Runs to completion with a generous budget, in one slice. */
static SimiStatus run_whole(struct SimiContext* ctx, const SimiObject* obj,
                            const char* entry, uint64_t* out) {
    if (simi_interp_init(ctx, obj, entry) != 0) return ctx->status;
    SimiStatus st;
    for (int guard = 0; guard < 1000; guard++) {
        st = simi_interp_run(ctx, 1000000);
        if (st != SIMI_STATUS_OK) break;
    }
    if (out) *out = ctx->result;
    return st;
}

static struct SimiContext ctx_a, ctx_b;

int main(void) {
    printf("=== in-kernel SIMI interpreter: corpus + resumability ===\n\n");

    /* ── Scenario 0: the kernel's mirrored ISA has not drifted ────────
     * kernel/simi_interp.h duplicates simi_isa.h's numbering rather than
     * including it (the convention kernel/simi_x86.h sets out). This
     * recomputes the fingerprint from the AUTHORITATIVE header in this TU
     * and compares against the value the interpreter's own TU produced
     * from its mirrored copy. A renumbered opcode fails here instead of
     * silently executing the wrong instruction. */
    {
        uint64_t authoritative =
              ((uint64_t)OP_COUNT      << 56)
            | ((uint64_t)OP_JMPR       << 48)
            | ((uint64_t)OP_RESOLVE    << 40)
            | ((uint64_t)OP_RET        << 32)
            | ((uint64_t)T_OBJREF      << 24)
            | ((uint64_t)REL_GEU       << 16)
            | ((uint64_t)SIMI_MAX_NAME <<  8)
            | ((uint64_t)FLAG_IMM);
        uint64_t mirrored = simi_interp_isa_fingerprint();
        CHECK(mirrored == authoritative,
              "ISA DRIFT GUARD: the kernel's mirrored opcode/type/relation numbering matches tools/simi/simi_isa.h exactly");
        if (mirrored != authoritative)
            printf("      (authoritative %016llx vs mirrored %016llx)\n",
                   (unsigned long long)authoritative, (unsigned long long)mirrored);
    }

    /* ── Scenario 1: agrees with the reference on the real corpus ────── */
    int loaded = 0;
    for (size_t i = 0; i < NCASES; i++) {
        SimiObject obj = {0};
        /* A corpus program that cannot be read is a FAILURE, not a skip.
         *
         * This used to print "(skip: ...)" and continue. The .tmo files are
         * build artifacts -- untracked, not gitignored, and produced by
         * nothing -- so on a fresh clone every one was missing, all twenty
         * cases skipped, and this test reported PASS having executed no SIMI
         * program whatsoever. The interpreter could have been arbitrarily
         * broken and this file would have said so cheerfully.
         *
         * That is the rule the guard scripts apply everywhere else, broken
         * here: a check that examined nothing must not pass. tests/run_all.sh
         * now assembles the corpus before running, so the files exist; this
         * makes their absence say so instead of hiding it. */
        if (simi_obj_read(cases[i].file, &obj) != 0) {
            CHECK(0, "corpus program is readable");
            printf("      cannot read %s -- build it with tools/simi/simi-asm,\n"
                   "      or run tests/run_all.sh which assembles the corpus first.\n",
                   cases[i].file);
            continue;
        }
        loaded++;
        uint64_t res = 0;
        SimiStatus st = run_whole(&ctx_a, &obj, cases[i].entry, &res);

        char msg[256];
        if (cases[i].expect_halt) {
            snprintf(msg, sizeof msg, "%s -> %lld (reference: %lld)",
                     cases[i].file, (long long)(int64_t)res, (long long)cases[i].result);
            CHECK(st == SIMI_STATUS_HALTED && (int64_t)res == cases[i].result, msg);
        } else {
            snprintf(msg, sizeof msg, "%s correctly refuses: %s",
                     cases[i].file, simi_status_name(cases[i].expect_status));
            CHECK(st == cases[i].expect_status, msg);
        }
        simi_obj_free(&obj);
    }
    CHECK(loaded > 0, "corpus programs were found and loaded");

    /* ── Scenario 2: THE resumability proof ──────────────────────────
     * Slicing execution must be invisible. Run loop_sum at every budget
     * from 1 to 40 and require identical results each time. Budget 1 means
     * a checkpoint boundary between literally every pair of instructions,
     * including mid-loop, on the taken branch, and across CALL/RET. */
    {
        SimiObject obj = {0};
        if (simi_obj_read("tools/simi/tests/loop_sum.tmo", &obj) == 0) {
            uint64_t whole = 0;
            run_whole(&ctx_a, &obj, "main", &whole);

            int all_match = 1; int first_bad = 0;
            for (uint64_t budget = 1; budget <= 40; budget++) {
                simi_interp_init(&ctx_b, &obj, "main");
                SimiStatus st = SIMI_STATUS_OK;
                for (int guard = 0; guard < 100000 && st == SIMI_STATUS_OK; guard++)
                    st = simi_interp_run(&ctx_b, budget);
                if (st != SIMI_STATUS_HALTED || ctx_b.result != whole) {
                    if (all_match) first_bad = (int)budget;
                    all_match = 0;
                }
            }
            CHECK(all_match,
                  "RESUMABILITY: executing in slices of every size 1..40 gives the identical result to one uninterrupted run");
            if (!all_match) printf("      (first divergent budget: %d)\n", first_bad);

            /* Budget of 1 is the extreme case worth naming separately: a
             * potential checkpoint between every single instruction. */
            simi_interp_init(&ctx_b, &obj, "main");
            uint64_t slices = 0; SimiStatus st = SIMI_STATUS_OK;
            while (st == SIMI_STATUS_OK && slices < 100000) { st = simi_interp_run(&ctx_b, 1); slices++; }
            CHECK(st == SIMI_STATUS_HALTED && ctx_b.result == whole,
                  "...including single-instruction slices -- a checkpoint boundary between EVERY instruction");
            printf("      (%llu single-instruction slices, result %lld, steps retired %llu)\n",
                   (unsigned long long)slices, (long long)(int64_t)ctx_b.result,
                   (unsigned long long)ctx_b.steps);
            simi_obj_free(&obj);
        }
    }

    /* ── Scenario 3: state is complete -- a byte copy resumes correctly ──
     * The claim underpinning checkpointing is that struct SimiContext IS
     * the execution state. Test it directly: run halfway, memcpy the
     * struct to a second context, and finish from the copy. If anything
     * lived outside the struct, the copy would not converge. This is a
     * checkpoint/restore in miniature, without touching disk. */
    {
        SimiObject obj = {0};
        if (simi_obj_read("tools/simi/tests/loop_sum.tmo", &obj) == 0) {
            uint64_t whole = 0;
            run_whole(&ctx_a, &obj, "main", &whole);

            simi_interp_init(&ctx_b, &obj, "main");
            simi_interp_run(&ctx_b, 7);                 /* partway in */
            CHECK(ctx_b.status == SIMI_STATUS_OK, "setup: context is mid-execution, not finished");

            static struct SimiContext clone;
            memcpy(&clone, &ctx_b, sizeof(clone));       /* the "checkpoint" */
            clone.obj = &obj;                            /* re-bind the immutable image, as restore would */

            SimiStatus st = SIMI_STATUS_OK;
            for (int g = 0; g < 100000 && st == SIMI_STATUS_OK; g++) st = simi_interp_run(&clone, 100);
            CHECK(st == SIMI_STATUS_HALTED && clone.result == whole,
                  "STATE COMPLETENESS: a raw byte copy of a mid-execution context resumes to the identical result");
            simi_obj_free(&obj);
        }
    }

    /* ── Scenario 4: traps are terminal and inspectable ──────────────── */
    {
        SimiObject obj = {0};
        if (simi_obj_read("tools/simi/tests/float_ops.tmo", &obj) == 0) {
            simi_interp_init(&ctx_a, &obj, "main");
            SimiStatus first = SIMI_STATUS_OK;
            for (int g = 0; g < 1000 && first == SIMI_STATUS_OK; g++) first = simi_interp_run(&ctx_a, 100);
            CHECK(first == SIMI_STATUS_TRAP_FLOAT_UNSUPPORTED, "a float program traps");
            CHECK(simi_interp_run(&ctx_a, 100) == first,
                  "...and re-running a trapped context returns the same trap without executing further");
            uint64_t steps_after = ctx_a.steps;
            simi_interp_run(&ctx_a, 100);
            CHECK(ctx_a.steps == steps_after,
                  "...retiring zero additional instructions -- a scheduler polling runnable contexts cannot resurrect it");
            simi_obj_free(&obj);
        }
    }

    /* ── Scenario 5: live-bytes accounting ───────────────────────────── */
    {
        SimiObject obj = {0};
        if (simi_obj_read("tools/simi/tests/add.tmo", &obj) == 0) {
            simi_interp_init(&ctx_a, &obj, "main");
            uint32_t live = simi_interp_live_bytes(&ctx_a);
            CHECK(live < sizeof(struct SimiContext),
                  "a depth-1 context's live bytes are far less than sizeof(SimiContext) -- checkpoints pay for depth actually used");
            printf("      (depth-1 live: %u B = %u NVMe frames; full struct: %u B)\n",
                   live, (live + 4095) / 4096, (unsigned)sizeof(struct SimiContext));
            simi_obj_free(&obj);
        }
    }

    printf("\n%d passed, %d failed\n", checks_passed, checks_failed);
    return checks_failed == 0 ? 0 : 1;
}
