/*
 * tls_cert_host_test.c — kernel/tls_cert.c: the validity strings a browser
 * will judge, and the refusals that keep a wrong one off the wire.
 *
 * Build and run:
 *   gcc -Wall -Wextra -std=c11 -DRTC_HOST_TEST -DRTC_TEST_HOOKS \
 *       -I . -I kernel -o /tmp/tls_cert_host_test \
 *       tests/tls_cert_host_test.c kernel/tls_cert.c kernel/rtc.c
 *   /tmp/tls_cert_host_test
 *
 * ─── What is worth testing here ────────────────────────────────────────────
 * mbedtls_x509write_crt_set_validity() checks the LENGTH of the string and
 * NOTHING ELSE. It compares strlen against 14 and copies. So the entire class
 * of bugs that keeps the length at 14 -- a month off by one, a century
 * mis-rounded, a truncating division that loses the last second of 1969 --
 * passes straight through into a signed certificate, and surfaces weeks later
 * as a browser saying only that the connection is not private.
 *
 * That makes this exactly the shape of code the rtc_host_test.c header
 * describes: the bugs that matter produce a VALID-LOOKING WRONG ANSWER, and
 * all of them live in pure logic a host can drive across dates no machine in
 * this project will ever hold.
 *
 * The expected strings are computed with Python's datetime and pasted in. Not
 * generated by this code, and not written from memory: the first draft of this
 * file had the 2400 leap-century constant wrong by six days, which makes three
 * separate times that one constant has been wrong here (rtc_host_test.c's
 * header records the other two). A wrong EXPECTED value is worse than no test,
 * because it gets "fixed" by breaking the implementation to match it.
 *
 * What this file does NOT cover, stated so it is not mistaken for coverage:
 * tls_cert_validity_window() reads the clock, so its rtc_get_unix() path is
 * not exercised here -- only the pure formatter and the argument refusals are.
 * The fail-closed behaviour when no clock is trusted needs the boot path, the
 * way entropy_init() did, and a unit test cannot see it.
 */

#include <stdio.h>
#include <string.h>
#include <stdint.h>
#include "tls_cert.h"
#include "rtc.h"

static int checks = 0, fails = 0;
static void ok(int cond, const char* what) {
    checks++;
    if (cond) printf("ok:   %s\n", what);
    else { printf("  FAIL  %s\n", what); fails++; }
}

/* Expected strings computed with Python's datetime -- an independent
 * implementation, never this code's own output, and never recollection. */
static const struct { uint64_t t; const char *want; const char *what; } VECTORS[] = {
    { 0ULL, "19700101000000", "the epoch itself" },
    { 1786490497ULL, "20260811232137", "HEAD's commit time, an ordinary 2026 date" },
    { 1709208000ULL, "20240229120000", "2024-02-29, an ordinary leap day" },
    { 4107542399ULL, "21000228235959", "2100-02-28T23:59:59Z -- the century that is NOT a leap year" },
    { 4107542400ULL, "21000301000000", "2100-03-01, the day after it" },
    { 13574606400ULL, "24000229120000", "2400-02-29 -- the century that IS a leap year" },
    { 951825600ULL, "20000229120000", "2000-02-29, the 400-rule leap year" },
    { 2524607999ULL, "20491231235959", "2049-12-31T23:59:59Z, last second mbedTLS writes as UTCTime" },
    { 2524608000ULL, "20500101000000", "2050-01-01T00:00:00Z, first second it writes as GeneralizedTime" },
    { 253402300799ULL, "99991231235959", "9999-12-31T23:59:59Z, the last 4-digit year" },
};

int main(void) {
    char buf[TLS_CERT_TIME_BUF];

    printf("=== tls_cert: validity strings ===\n\n");

    for (unsigned i = 0; i < sizeof VECTORS / sizeof VECTORS[0]; i++) {
        memset(buf, '#', sizeof buf);
        int rc = tls_cert_format_time(VECTORS[i].t, buf, sizeof buf);
        char msg[220];
        if (rc != TLS_CERT_OK) {
            snprintf(msg, sizeof msg, "%s -- returned %d", VECTORS[i].what, rc);
            ok(0, msg);
            continue;
        }
        snprintf(msg, sizeof msg, "%s -> %s", VECTORS[i].what, buf);
        ok(strcmp(buf, VECTORS[i].want) == 0, msg);
    }

    printf("\n=== the length mbedTLS actually checks ===\n\n");
    ok(TLS_CERT_TIME_LEN == 14, "TLS_CERT_TIME_LEN is 14, matching set_validity");
    tls_cert_format_time(1786490497ULL, buf, sizeof buf);
    ok(strlen(buf) == 14, "a formatted timestamp is exactly 14 characters");
    ok(buf[14] == '\0', "and NUL-terminated at index 14");
    ok(strchr(buf, 'Z') == NULL,
       "with no trailing Z -- mbedTLS writes that itself into index 14");
    int alldig = 1;
    for (int i = 0; i < 14; i++) if (buf[i] < '0' || buf[i] > '9') alldig = 0;
    ok(alldig, "all 14 characters are digits");

    printf("\n=== refusals ===\n\n");
    /* Every one of these returns without touching the buffer, so the sentinel
     * fill must survive. A caller that ignores the return gets its own
     * uninitialised memory, not a plausible wrong date. */
    memset(buf, '#', sizeof buf);
    ok(tls_cert_format_time(0, buf, 14) == TLS_CERT_E_BADARG,
       "a 14-byte buffer is refused -- 14 characters need 15 bytes with the NUL");
    ok(buf[0] == '#', "  and the short buffer was not written to");

    ok(tls_cert_format_time(0, NULL, TLS_CERT_TIME_BUF) == TLS_CERT_E_BADARG,
       "a NULL buffer is refused");

    /* 253402300800 is 10000-01-01T00:00:00Z. x509_write_time() picks UTCTime
     * vs GeneralizedTime by reading the first three characters as text, so a
     * five-digit year does not look wrong -- it silently selects the wrong
     * ASN.1 type and then truncates at the wrong offset. */
    memset(buf, '#', sizeof buf);
    ok(tls_cert_format_time(253402300800ULL, buf, sizeof buf) == TLS_CERT_E_RANGE,
       "year 10000 is refused rather than encoded as a wrong ASN.1 type");
    ok(buf[0] == '#', "  and the buffer was not written to");

    printf("\n=== the window ===\n\n");
    char nb[TLS_CERT_TIME_BUF], na[TLS_CERT_TIME_BUF];
    ok(tls_cert_validity_window(0, nb, sizeof nb, na, sizeof na) == TLS_CERT_E_BADARG,
       "a zero lifetime is refused");
    ok(tls_cert_validity_window(3600, nb, 14, na, sizeof na) == TLS_CERT_E_BADARG,
       "a short notBefore buffer is refused");
    ok(TLS_CERT_BACKDATE_SECONDS == 86400ULL,
       "notBefore is backdated a full day, not a second (see the design doc)");


    /* ─── rtc_break_down directly, because tls_cert cannot reach half of it ──
     * tls_cert_format_time() takes a uint64_t, so no vector above can ever
     * drive a negative time -- and the floor-division branch in
     * rtc_break_down() exists ONLY for negative times. Left at that, this file
     * would have zero coverage of the one line its own source comment calls
     * "the whole reason" the parameter is signed.
     *
     * It is not dead code: mbedtls_platform_gmtime_r() shares this function
     * and is handed peer certificate dates, which a hostile or merely broken
     * peer can set before 1970. C truncates toward zero, so without the
     * correction -1/86400 is 0 and the last second of 1969 decodes as
     * 1970-01-01T00:00:-1 -- in range, plausible, and wrong.
     *
     * Expected values from Python's datetime, as above. C's tm_wday is Sun=0;
     * 1970-01-01 was a Thursday, so day 0 is 4. */
    printf("\n=== rtc_break_down: the pre-1970 path tls_cert cannot reach ===\n\n");
    {
        int64_t y; unsigned mo, d, h, mi, se; int wd;

        rtc_break_down(-1, &y, &mo, &d, &h, &mi, &se, &wd);
        ok(y == 1969 && mo == 12 && d == 31 && h == 23 && mi == 59 && se == 59,
           "t = -1 is 1969-12-31T23:59:59Z, not 1970-01-01T00:00:-1");

        rtc_break_down(-86400, &y, &mo, &d, &h, &mi, &se, &wd);
        ok(y == 1969 && mo == 12 && d == 31 && h == 0 && mi == 0 && se == 0,
           "t = -86400 is exactly one day before the epoch");

        rtc_break_down(-86401, &y, &mo, &d, &h, &mi, &se, &wd);
        ok(y == 1969 && mo == 12 && d == 30 && h == 23 && mi == 59 && se == 59,
           "t = -86401 crosses a second day boundary correctly");

        rtc_break_down(-2208988800LL, &y, &mo, &d, &h, &mi, &se, &wd);
        ok(y == 1900 && mo == 1 && d == 1 && h == 0 && mi == 0 && se == 0,
           "t = -2208988800 is 1900-01-01, the non-leap century going backwards");
        /* 1900-01-01 was a Monday, so tm_wday 1. This check exists because
         * mutation testing found the suite did NOT catch removal of the
         * negative-weekday correction: at t = -86400 the expression
         * (days + 4) %% 7 is still positive, so the only vectors that can see
         * the bug are ones more than four days before the epoch. A test that
         * cannot fail was passing. */
        ok(wd == 1, "1900-01-01 is a Monday -- (days + 4) %% 7 is negative here");

        rtc_break_down(0, &y, &mo, &d, &h, &mi, &se, &wd);
        ok(wd == 4, "the epoch is a Thursday (tm_wday 4, Sun=0)");
        rtc_break_down(-86400, &y, &mo, &d, &h, &mi, &se, &wd);
        ok(wd == 3, "the day before it is a Wednesday, not a negative weekday");

        /* Every out-parameter is documented optional. A NULL deref here would
         * be a crash in the certificate path, so it is worth one line. */
        rtc_break_down(1786490497LL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
        ok(1, "all-NULL out-parameters do not fault");
    }

    printf("\n---- checks=%d failed=%d\n", checks, fails);
    return fails ? 1 : 0;
}
