/* user/examples/simi_recycle.c — Phase 14b/14c SIMI activation-cache
 * teardown verification
 *
 * Proves that destroying a partition reclaims the SIMI activation-cache
 * code frames its objects' spawns cached, via repeated create → assign →
 * valloc → upload-SIMI → spawn → destroy cycles from ring-3, and that a
 * vfree'd (retired) activation's frames are freed the moment the LAST
 * process mapping them exits. Each cycle, THIS process (spawned via HTTP
 * while uid 1000 was unassigned, so it lives in the default partition and
 * survives every destroy below) does:
 *
 *   1. sls_partition_create() — a fresh partition.
 *   2. sls_partition_assign(uid 1000) — route uid 1000 into it.
 *   3. sls_obj_valloc() — a fresh OBJ_TYPE_PROGRAM object with a
 *      cycle-unique name and owner_uid=1000; partition_id 0 defaults to
 *      the owner's current partition (the ONLY way to get an object whose
 *      partition matches what catalog_check_access() compares at spawn).
 *   4. sls_upload_binary() — the embedded SIMI .tmo fixture
 *      (simi_recycle_tmo_blob.h, regenerated by the Makefile from
 *      tools/simi/tests/add.simi — a 104-byte SIMI object whose main
 *      computes 2+3 and returns 5), completing the object.
 *   5. sls_program_spawn() TWICE (synchronous). The first spawn is an
 *      activation-cache MISS: simi_translate_and_map() translates the
 *      .tmo to native x86-64, allocates the shared code frames, maps them
 *      + a fresh per-activation scratch page, and the child runs the
 *      translated add.tmo (2+3 -> r0=5) and exits via the kernel-appended
 *      SYS_SLS_EXIT stub. The second spawn is a cache HIT: same code
 *      frames mapped, fresh scratch page, no re-translation — proving the
 *      shared-frame path still works while the activation is live.
 *   6. sls_partition_destroy() — kills any remaining process, vfrees the
 *      catalog objects / binary slots, and (Phase 14b) frees this
 *      partition's SIMI activation code frames via simi_vfree_partition().
 *
 * The destroy tooth is arithmetic: the activation cache has 16 slots
 * (SIMI_MAX_ACTIVATIONS == MAX_SERVICE_BINARIES). Every cycle uses a
 * unique object name (simo0..simo17). WITHOUT the destroy-time activation
 * free, the slots fill up and cycle 16's spawn logs "activation table is
 * full ... every spawn will retranslate" — the boot check greps for that
 * line's absence and for 18 per-cycle activation-vfree lines. WITH the
 * fix, every destroy returns its partition's slots and all 18 cycles stay
 * cached.
 *
 * The Phase 14c eager-free probe (after the 18 cycles) proves the
 * refcount half: a gated (HELD) async spawn maps the translated frames
 * with mappers=1 but never runs; the object is then vfree'd while that
 * mapper is LIVE — the activation must be RETIRED (frames held), not
 * freed — and killing the held child drops the refcount to 0, which must
 * free the frames IMMEDIATELY (the kernel logs "last mapper exited"),
 * not at the probe partition's destroy. The boot check greps for both
 * log lines.
 *
 * Build:
 *   make user-programs
 *   python3 utils/program_upload.py --file user/examples/simi_recycle.bin \
 *                                   --name simi_recycle
 *   (spawn simi_recycle via POST /api/program/spawn with dave's token)
 */

#include <sls.h>
#include <aerocap_provision.h>
#include "simi_recycle_tmo_blob.h"

/* The boot check spawns this program with dave's token → owner_uid 1000.
 * Children spawned by it inherit that uid (syscall_dispatch.c's
 * spawn_owner_uid), so assigning 1000 routes them into the fresh partition. */
#define DEMO_UID 1000
/* 16 cache slots + 2: cycles 16-17 are the tooth (see header comment). */
#define CYCLES   18

/* SYS_SLS_PROC_KILL (161) — the kernel's syscall_dispatch.c dispatches it
 * with the pid as the bare argument (0 = self), no request struct. Not in
 * sls.h (the demo binary hardcodes it); keep the number in sync with
 * kernel/syscall_dispatch.c. */
#define SLS_SYS_PROC_KILL 161

static void put_u32(uint32_t v) {
    char buf[12];
    int i = 11;
    buf[11] = 0;
    if (v == 0) buf[--i] = '0';
    while (v) { buf[--i] = (char)('0' + (v % 10)); v /= 10; }
    sls_puts(&buf[i]);
}

/* "scycle0" .. "scycle17" — unique partition names keep the boot log
 * readable (names are not required to be unique; ids come from slot
 * reuse). */
static void build_name(char* out, const char* base, uint32_t n) {
    int i = 0;
    while (base[i]) { out[i] = base[i]; i++; }
    char digits[8];
    int d = 0;
    uint32_t v = n;
    do { digits[d++] = (char)('0' + (v % 10)); v /= 10; } while (v);
    while (d > 0) out[i++] = digits[--d];
    out[i] = '\0';
}

static void make_part_name(char* out, uint32_t cycle) {
    build_name(out, "scycle", cycle);
}

/* "simo0" .. "simo17" — the cycle's SIMI PROGRAM object name. Unique per
 * cycle so it never collides with the catalog and never reuses an
 * activation slot across cycles (each destroy frees its own). */
static void make_obj_name(char* out, uint32_t cycle) {
    const char* base = "simo";
    int i = 0;
    while (base[i]) { out[i] = base[i]; i++; }
    out[i] = (char)('0' + cycle);
    out[i + 1] = '\0';
}

int main(void) {
    sls_puts("[sirc] SIMI activation teardown recycle test starting\n");
    int fail = 0;

    for (uint32_t cycle = 0; cycle < CYCLES; cycle++) {
        /* 1. Fresh partition (destroy reuses the slot). */
        char part_name[32];   /* PARTITION_NAME_LEN */
        make_part_name(part_name, cycle);
        uint64_t part_id = sls_partition_create(part_name);
        if (part_id == SLS_PARTITION_INVALID_ID) {
            sls_puts("[sirc] partition_create FAILED at cycle ");
            put_u32(cycle);
            sls_puts("\n");
            return 1;
        }

        /* 2. Route uid 1000 into it. */
        if (sls_partition_assign(DEMO_UID, (uint32_t)part_id) != 0) {
            sls_puts("[sirc] partition_assign FAILED at cycle ");
            put_u32(cycle);
            sls_puts("\n");
            return 1;
        }

        /* 3. Create the SIMI object IN this partition. */
        char obj_name[SLS_NAME_LEN];
        make_obj_name(obj_name, cycle);
        uint64_t obj_id = 0;
        if (sls_obj_valloc(obj_name, SLS_OBJ_PROGRAM, 4 /* pages */,
                           DEMO_UID,
                           SLS_PERM_READ | SLS_PERM_EXECUTE | SLS_PERM_OWNER,
                           0 /* partition: default to owner's */,
                           &obj_id) != 0) {
            sls_puts("[sirc] valloc FAILED at cycle ");
            put_u32(cycle);
            sls_puts("\n");
            return 1;
        }

        /* 4. Upload the embedded SIMI .tmo (single chunk, final). The
         * kernel detects SIMI_MAGIC and marks the slot is_simi, so the
         * spawn below goes through simi_translate_and_map(). */
        if (sls_upload_binary(obj_name, SIMI_RECYCLE_TMO_BLOB,
                              SIMI_RECYCLE_TMO_BLOB_LEN, 0, 1) != 0) {
            sls_puts("[sirc] upload FAILED at cycle ");
            put_u32(cycle);
            sls_puts("\n");
            return 1;
        }

        /* 5. Synchronous spawn — MISS, then HIT. The child runs the
         * translated add.tmo (2+3 -> r0=5) and exits via the stub. */
        if (sls_program_spawn(obj_name) == 0) {
            sls_puts("[sirc] spawn #1 (MISS) FAILED at cycle ");
            put_u32(cycle);
            sls_puts("\n");
            return 1;
        }
        if (sls_program_spawn(obj_name) == 0) {
            sls_puts("[sirc] spawn #2 (HIT) FAILED at cycle ");
            put_u32(cycle);
            sls_puts("\n");
            return 1;
        }

        /* 6. Destroy the partition — kills any remaining process, vfrees
         * its catalog objects / binary slots, and frees this partition's
         * SIMI activation code frames (Phase 14b). */
        if (sls_partition_destroy((uint32_t)part_id) != 0) {
            sls_puts("[sirc] partition_destroy FAILED at cycle ");
            put_u32(cycle);
            sls_puts("\n");
            fail = 1;
        }

        sls_puts("[sirc] cycle ");
        put_u32(cycle);
        sls_puts(" ok\n");
    }

    /* ── Phase 14c probe: eager free on the last mapper's exit ─────────────
     *
     * Proves the mapper refcount reclaims a retired activation's frames
     * the moment the last live mapper dies, not at partition destroy.
     * Sequence: gated async spawn (the child is HELD — never scheduled —
     * but its page table ALREADY maps the translated code frames, so the
     * activation's mappers=1), vfree the object while that mapper is live
     * (the activation must be RETIRED, frames held — the kernel logs
     * "retired, 1 live mapper(s)"), then kill the held child (its
     * teardown walk decrements mappers to 0, which must free the frames
     * NOW — the kernel logs "last mapper exited"). The probe partition's
     * destroy then has nothing SIMI left to free: the boot check asserts
     * the eager-free line exists and that the probe contributes no
     * destroy-time activation-vfree line. */
#define EAGER_OBJ "simoeager"
    {
        char pname[32];
        build_name(pname, "seager", 0);
        uint64_t pid3 = sls_partition_create(pname);
        int probe_ok = 0;
        if (pid3 != SLS_PARTITION_INVALID_ID &&
            sls_partition_assign(DEMO_UID, (uint32_t)pid3) == 0) {
            uint64_t oid = 0;
            if (sls_obj_valloc(EAGER_OBJ, SLS_OBJ_PROGRAM, 4 /* pages */,
                               DEMO_UID,
                               SLS_PERM_READ | SLS_PERM_EXECUTE | SLS_PERM_OWNER,
                               0 /* partition: default to owner's */,
                               &oid) == 0 &&
                sls_upload_binary(EAGER_OBJ, SIMI_RECYCLE_TMO_BLOB,
                                  SIMI_RECYCLE_TMO_BLOB_LEN, 0, 1) == 0) {
                uint64_t held = sls_program_spawn_nb_held(EAGER_OBJ);
                if (held != 0 &&
                    sls_obj_vfree(EAGER_OBJ) == 0 &&
                    _sls_syscall(SLS_SYS_PROC_KILL,
                                 (void*)(uintptr_t)held) == 0) {
                    probe_ok = 1;
                }
            }
        }
        if (pid3 != SLS_PARTITION_INVALID_ID)
            sls_partition_destroy((uint32_t)pid3);
        if (probe_ok) {
            sls_puts("[sirc] eager-free probe DONE\n");
        } else {
            sls_puts("[sirc] eager-free probe FAILED\n");
            fail = 1;
        }
    }

    sls_puts(fail ? "[sirc] done (FAILURES)\n"
                  : "[sirc] DONE: 18/18 cycles passed\n");
    return fail;
}
