#ifndef BUNDLE_H
#define BUNDLE_H

#include <stdint.h>

// One entry in the compiled-in static asset table.
// Generated by tools/bundle_webapp.py from slsos-sim/dist/.
struct BundleAsset {
    const char*    path;   // URL path, e.g. "/assets/index-abc123.js"
    const char*    mime;   // MIME type string
    const uint8_t* data;   // raw bytes (in .rodata)
    uint32_t       len;    // byte count
};

// Look up a URL path in the compiled-in bundle.
// "/" and "/index.html" both return the SPA root.
// Returns NULL if the path is not in the bundle.
const struct BundleAsset* bundle_find(const char* path);

#endif /* BUNDLE_H */
