//! Common Lisp code generator — reads the typed AST JSON and emits a complete
//! Common Lisp file with package definition, type definitions, opcode constants,
//! service method stubs, and an `ecase`-based dispatch table.
//!
//! Usage:
//! ```text
//! aeroidl <input.aeroidl> --target lisp        # emit to stdout
//! aeroidl <input.aeroidl> --target lisp -o out.lisp
//! ```

use serde_json::Value;

// ── Public API ──────────────────────────────────────────────────────────────

/// Emit a complete Common Lisp file from the typed AST JSON.
pub fn emit_lisp(ast: &Value) -> String {
    let mut out = String::with_capacity(8192);

    let namespace = ast["namespace"].as_str().unwrap_or("unknown");
    let version = ast["version"].as_str().unwrap_or("unknown");
    let mod_name = to_lisp_name(namespace);

    // Header comment
    out.push_str(&format!(";;; {mod_name}.lisp — Auto-generated by aeroidl-cl v0.1\n"));
    out.push_str(&format!(";;; AeroIDL version: {version}\n"));
    out.push_str(";;;\n");
    out.push_str(";;; This file implements the Lisp-side dispatch table and FFI wrappers.\n");
    out.push_str(";;; The Lisp sidecar receives SEND_CAP messages on its channel,\n");
    out.push_str(";;; dispatches by opcode, and replies with RECV_CAP messages.\n");
    out.push_str(";;;\n");
    out.push_str(";;; The sidecar runtime (loaded separately) provides:\n");
    out.push_str(";;;   (aerosls:chan-send), (aerosls:chan-recv), (aerosls:arena-alloc),\n");
    out.push_str(";;;   (aerosls:arena-free), (aerosls:arena-mem)\n");
    out.push('\n');

    // Package definition
    let pkg = to_lisp_package(namespace);
    let exports = collect_exports(ast);
    out.push_str(&format!("(defpackage #:aerosls.{pkg}\n"));
    out.push_str("  (:use #:cl #:aerosls)\n");
    out.push_str("  (:export\n");
    for e in &exports {    out.push_str(&format!(
                "           #:#{e}\n"
            ));
    }
    out.push_str("           ))\n\n");
    out.push_str(&format!("(in-package #:aerosls.{pkg})\n\n"));

    // ── Opcode constants ──────────────────────────────────────────────────
    out.push_str(";;; ─── Constants ─────────────────────────────────────────────────────────\n\n");
    if let Some(interfaces) = ast["interfaces"].as_array() {
        for iface in interfaces {
            let methods = iface["methods"].as_array().map_or(&[] as &[Value], |v| v.as_slice());
            for m in methods {
                let mname = m["name"].as_str().unwrap();
                let opcode = m["opcode"].as_u64().unwrap();
                let const_name = format!("+op-{}+", to_lisp_snake(mname));
                out.push_str(&format!(
                    "(defconstant {const_name:<28} #x{:04X})\n",
                    opcode
                ));
            }
        }
    }
    out.push('\n');

    // ── Enum types ────────────────────────────────────────────────────────
    if let Some(enums) = ast["enums"].as_array() {
        if !enums.is_empty() {
            out.push_str(";;; ─── Enum types ────────────────────────────────────────────────────────\n\n");
            for e in enums {
                emit_lisp_enum(&mut out, e);
            }
        }
    }

    // ── Struct types ──────────────────────────────────────────────────────
    if let Some(structs) = ast["structs"].as_array() {
        if !structs.is_empty() {
            out.push_str(";;; ─── Struct types ──────────────────────────────────────────────────────\n\n");
            for s in structs {
                emit_lisp_struct(&mut out, s, ast);
            }
        }
    }

    // ── Result wrapper ────────────────────────────────────────────────────
    out.push_str(";;; ─── Result wrapper ───────────────────────────────────────────────────\n\n");
    emit_lisp_result_wrapper(&mut out, ast);

    // ── Service methods (stubs) ───────────────────────────────────────────
    if let Some(interfaces) = ast["interfaces"].as_array() {
        for iface in interfaces {
            let iface_name = iface["name"].as_str().unwrap();
            let methods = iface["methods"].as_array().map_or(&[] as &[Value], |v| v.as_slice());
            let pkg_prefix = to_lisp_snake(iface_name);

            out.push_str(&format!(";;; ─── {iface_name} methods ───────────────────────────────────────────\n\n"));

            for m in methods {
                emit_lisp_method_stub(&mut out, m, &pkg_prefix, ast);
            }
        }
    }

    // ── Dispatch table ────────────────────────────────────────────────────
    if let Some(interfaces) = ast["interfaces"].as_array() {
        for iface in interfaces {
            let iface_name = iface["name"].as_str().unwrap();
            let pkg_prefix = to_lisp_snake(iface_name);
            let methods = iface["methods"].as_array().map_or(&[] as &[Value], |v| v.as_slice());

            out.push_str(&format!(";;; ─── {iface_name} dispatch table ────────────────────────────────────\n\n"));
            emit_lisp_dispatch(&mut out, methods, &pkg_prefix, ast);
        }
    }

    // ── Bootstrap registration ────────────────────────────────────────────
    if let Some(interfaces) = ast["interfaces"].as_array() {
        for iface in interfaces {
            let iface_name = iface["name"].as_str().unwrap();
            let pkg_prefix = to_lisp_snake(iface_name);

            out.push_str(&format!(";;; ─── Bootstrap: register {iface_name} with the sidecar runtime ─────\n\n"));
            let reg_fn = format!("register-{}-service", pkg_prefix.replace("-service", ""));
            out.push_str(&format!(
                "(defun {reg_fn} (chan-endpoint)\n"
            ));
            out.push_str(&format!(
                "  \"Called during sidecar bootstrap to register the dispatch function.\"\n"
            ));
            out.push_str(&format!(
                "  (setf (getf *service-dispatch-table* :{pkg_prefix})\n"
            ));
            out.push_str(&format!(
                "        (cons chan-endpoint #'#{pkg_prefix}-dispatch))\n"
            ));
            out.push_str(&format!(
                "  (format *debug-io* \"[aeroidl] {iface_name} registered on endpoint ~A~%\"\n"
            ));
            out.push_str(&format!("          chan-endpoint))\n\n"));
        }
    }

    out
}

// ── Enum generation ─────────────────────────────────────────────────────────

fn emit_lisp_enum(out: &mut String, e: &Value) {
    let name = e["name"].as_str().unwrap();
    let variants = e["variants"].as_array().unwrap();
    let lisp_name = to_lisp_snake(name);

    // Type definition using MEMBER
    out.push_str(&format!("(deftype {lisp_name}-kind ()\n"));
    out.push_str("  '(member");
    for v in variants {
        let vname = v["name"].as_str().unwrap();
        out.push_str(&format!(" :{}", to_lisp_snake(vname)));
    }
    out.push_str("))\n\n");

    // Discriminant-to-keyword mapping
    out.push_str(&format!("(defun {lisp_name}-disc-to-keyword (disc)\n"));
    out.push_str(&format!("  \"Convert a numeric discriminant to a keyword.\"\n"));
    out.push_str("  (case disc\n");
    for v in variants {
        let vname = v["name"].as_str().unwrap();
        let disc = v["discriminant"].as_i64().unwrap();
        out.push_str(&format!("    ({disc} :{})\n", to_lisp_snake(vname)));
    }
    out.push_str("    (otherwise :internal)))\n\n");

    // Keyword-to-discriminant mapping
    out.push_str(&format!("(defun {lisp_name}-keyword-to-disc (kw)\n"));
    out.push_str(&format!("  \"Convert a keyword to its numeric discriminant.\"\n"));
    out.push_str("  (case kw\n");
    for v in variants {
        let vname = v["name"].as_str().unwrap();
        let disc = v["discriminant"].as_i64().unwrap();
        out.push_str(&format!("    (:{} {disc})\n", to_lisp_snake(vname)));
    }
    out.push_str("    (otherwise 0)))\n\n");
}

// ── Struct generation ───────────────────────────────────────────────────────

fn emit_lisp_struct(out: &mut String, s: &Value, ast: &Value) {
    let name = s["name"].as_str().unwrap();
    let fields = s["fields"].as_array().unwrap();
    let lisp_name = to_lisp_snake(name);
    let constructor = format!("make-{lisp_name}");

    out.push_str(&format!("(defstruct ({lisp_name} (:constructor {constructor}"));
    // Add constructor parameter list for simple structs
    let ctor_params: Vec<String> = fields
        .iter()
        .map(|f| {
            let fname = f["name"].as_str().unwrap();
            format!("({})", to_lisp_snake(fname))
        })
        .collect();
    if !ctor_params.is_empty() {
        out.push_str(&format!(" ({})", ctor_params.join(" ")));
    }
    out.push_str("))\n");

    for f in fields {
        let fname = f["name"].as_str().unwrap();
        let lisp_fname = to_lisp_snake(fname);
        let lisp_type = json_type_to_lisp_type(&f["ty"], ast);
        let wire_size = f["wire_size"].as_u64().unwrap_or(0);

        if wire_size > 0 && wire_size <= 8 {
            // Simple field with default
            let default = lisp_type_default(&f["ty"]);
            out.push_str(&format!(
                "  ({lisp_fname:<20} {default:<16} :type {lisp_type})\n"
            ));
        } else {
            // Arena/cap handle field
            out.push_str(&format!(
                "  ({lisp_fname:<20} 0                 :type (unsigned-byte 16))  ; MEM cap handle\n"
            ));
        }
    }
    out.push_str(")\n\n");
}

// ── Result wrapper ──────────────────────────────────────────────────────────

fn emit_lisp_result_wrapper(out: &mut String, ast: &Value) {
    // Collect all interface names to generate per-interface result types
    if let Some(interfaces) = ast["interfaces"].as_array() {
        for iface in interfaces {
            let iface_name = iface["name"].as_str().unwrap();
            let pkg_prefix = to_lisp_snake(iface_name);
            let methods = iface["methods"].as_array().map_or(&[] as &[Value], |v| v.as_slice());

            // Collect error enum names from return types
            let mut error_types: Vec<String> = Vec::new();
            for m in methods {
                if let Some(ret) = m.get("return_type") {
                    if ret["kind"].as_str() == Some("result") {
                        if let Some(err_type) = ret.get("inner2") {
                            if err_type["kind"].as_str() == Some("named") {
                                let err_name = err_type["name"].as_str().unwrap().to_string();
                                if !error_types.contains(&err_name) {
                                    error_types.push(err_name);
                                }
                            }
                        }
                    }
                }
            }

            // Generate a result struct for this interface
            out.push_str(&format!("(defstruct {pkg_prefix}-result\n"));
            out.push_str("  (ok    nil :type boolean)\n");
            out.push_str("  (value nil)          ; raw value on success\n");
            out.push_str("  (error nil))         ; error struct on failure\n\n");

            // Success constructor
            out.push_str(&format!(
                "(defun {pkg_prefix}-success (value)\n"
            ));
            out.push_str(&format!(
                "  (make-{pkg_prefix}-result :ok t :value value))\n\n"
            ));

            // Failure constructor
            if !error_types.is_empty() {
                let err_type = &error_types[0];
                let err_lisp = to_lisp_snake(err_type);
                out.push_str(&format!(
                    "(defun {pkg_prefix}-failure (kind message)\n"
                ));
                out.push_str(&format!(
                    "  (make-{pkg_prefix}-result :ok nil\n"
                ));
                out.push_str(&format!(
                    "    :error (make-{err_lisp} :kind kind :message message)))\n\n"
                ));
            }
        }
    }
}

// ── Method stub generation ──────────────────────────────────────────────────

fn emit_lisp_method_stub(out: &mut String, m: &Value, pkg_prefix: &str, ast: &Value) {
    let mname = m["name"].as_str().unwrap();
    let lisp_mname = format!("{}-{}", pkg_prefix, to_lisp_snake(mname));
    let params = m["params"].as_array().unwrap();
    let return_type = &m["return_type"];

    // Build parameter list
    let param_strs: Vec<String> = params
        .iter()
        .map(|p| {
            let pname = p["name"].as_str().unwrap();
            let lisp_type = json_type_to_lisp_param_type(p, ast);
            format!("({} {})", to_lisp_snake(pname), lisp_type)
        })
        .collect();

    // Docstring
    let param_doc: Vec<String> = params
        .iter()
        .map(|p| {
            let pname = p["name"].as_str().unwrap();
            let ty = &p["ty"];
            let ownership = p["ownership"].as_str().unwrap_or("inline");
            let ty_str = json_type_to_lisp_type(ty, ast);
            format!("{pname}: {ty_str}@{ownership}")
        })
        .collect();

    out.push_str(&format!("(defun {lisp_mname} ({})\n", param_strs.join(" ")));
    out.push_str(&format!(
        "  \"{}({})\"\n",
        mname,
        param_doc.join(", ")
    ));

    // Type declarations
    if !params.is_empty() {
        let decls: Vec<String> = params
            .iter()
            .map(|p| {
                let pname = p["name"].as_str().unwrap();
                let lisp_type = json_type_to_lisp_param_type(p, ast);
                format!("(type {lisp_type} {})", to_lisp_snake(pname))
            })
            .collect();
        out.push_str(&format!("  (declare (type (values {})))\n", decls.join(" ")));
    }

    // Generate stub body based on return type
    let return_kind = return_type["kind"].as_str().unwrap_or("unit");
    match return_kind {
        "result" => {
            let ok_type = return_type.get("inner");
            let ok_kind = ok_type
                .and_then(|t| t.get("kind"))
                .and_then(|k| k.as_str())
                .unwrap_or("unit");
            match ok_kind {
                "unit" => {
                    out.push_str(&format!(
                        "  ({pkg_prefix}-success nil))\n\n"
                    ));
                }
                "i32" | "u32" => {
                    out.push_str(&format!(
                        "  ({pkg_prefix}-success 0))  ; TODO: implement\n\n"
                    ));
                }
                "i64" | "u64" => {
                    out.push_str(&format!(
                        "  ({pkg_prefix}-success 0))  ; TODO: implement\n\n"
                    ));
                }
                "f64" => {
                    out.push_str(&format!(
                        "  ({pkg_prefix}-success 0.0d0))  ; TODO: implement\n\n"
                    ));
                }
                "named" => {
                    let type_name = return_type["inner"]["name"].as_str().unwrap_or("nil");
                    let lisp_type = to_lisp_snake(type_name);
                    out.push_str(&format!(
                        "  ({pkg_prefix}-success (make-{lisp_type})))  ; TODO: implement\n\n"
                    ));
                }
                "array" => {
                    out.push_str(&format!(
                        "  ({pkg_prefix}-success 0))  ; TODO: return arena cap handle\n\n"
                    ));
                }
                _ => {
                    out.push_str(&format!(
                        "  ({pkg_prefix}-success nil))  ; TODO: implement\n\n"
                    ));
                }
            }
        }
        "unit" => {
            out.push_str("  (values))\n\n");
        }
        "named" => {
            let type_name = return_type["name"].as_str().unwrap_or("nil");
            let lisp_type = to_lisp_snake(type_name);
            out.push_str(&format!(
                "  (make-{lisp_type}))  ; TODO: implement\n\n"
            ));
        }
        _ => {
            out.push_str("  nil)  ; TODO: implement\n\n");
        }
    }
}

// ── Dispatch table ──────────────────────────────────────────────────────────

fn emit_lisp_dispatch(out: &mut String, methods: &[Value], pkg_prefix: &str, ast: &Value) {
    out.push_str(&format!(
        "(defun {pkg_prefix}-dispatch (opcode payload payload-len cap-slots n-caps)\n"
    ));
    out.push_str("  \"Main entry point called by the Lisp sidecar's channel event loop.\n");
    out.push_str("   Decodes the opcode and arguments from the payload bytes, calls the\n");
    out.push_str("   appropriate method, and returns (values reply-payload reply-caps).\"\n");
    out.push_str("  (declare (type (unsigned-byte 16) opcode)\n");
    out.push_str("           (type (simple-array (unsigned-byte 8)) payload)\n");
    out.push_str("           (type fixnum payload-len)\n");
    out.push_str("           (type (simple-array (unsigned-byte 16)) cap-slots)\n");
    out.push_str("           (type (unsigned-byte 8) n-caps))\n");
    out.push('\n');

    // encode-result helper
    out.push_str("  (flet ((encode-result (result)\n");
    out.push_str(&format!(
        "           \"Encode a {pkg_prefix}-result into reply payload bytes + reply caps.\"\n"
    ));
    out.push_str("           (let ((reply-payload (make-array 32 :element-type '(unsigned-byte 8)\n");
    out.push_str("                                                :initial-element 0))\n");
    out.push_str("                 (reply-caps    (make-array 8  :element-type '(unsigned-byte 16)\n");
    out.push_str("                                                :initial-element 0))\n");
    out.push_str("                 (n-reply-caps  0))\n");
    out.push_str(&format!(
        "             (if ({pkg_prefix}-result-ok result)\n"
    ));
    out.push_str("                 (progn\n");
    out.push_str("                   (setf (aref reply-payload 0) 1)   ; ok = true\n");
    out.push_str(&format!(
        "                   (let ((v ({pkg_prefix}-result-value result)))\n"
    ));
    out.push_str("                     (etypecase v\n");
    out.push_str("                       ((unsigned-byte 32)\n");
    out.push_str(
        "                        (setf (aref reply-payload 4) (ldb (byte 8 0) v))\n",
    );
    out.push_str(
        "                        (setf (aref reply-payload 5) (ldb (byte 8 8) v))\n",
    );
    out.push_str(
        "                        (setf (aref reply-payload 6) (ldb (byte 8 16) v))\n",
    );
    out.push_str(
        "                        (setf (aref reply-payload 7) (ldb (byte 8 24) v)))\n",
    );
    out.push_str("                       ((signed-byte 64)\n");
    out.push_str(
        "                        (dotimes (i 8)\n",
    );
    out.push_str(
        "                          (setf (aref reply-payload (+ 8 i))\n",
    );
    out.push_str(
        "                                (ldb (byte 8 (* 8 i)) v))))\n",
    );
    out.push_str("                       (double-float\n");
    out.push_str("                        (let ((bits (sb-kernel:double-float-bits v)))\n");
    out.push_str(
        "                          (dotimes (i 8)\n",
    );
    out.push_str(
        "                            (setf (aref reply-payload (+ 8 i))\n",
    );
    out.push_str(
        "                                  (ldb (byte 8 (* 8 i)) bits)))))\n",
    );
    out.push_str("                       ((unsigned-byte 16)  ; MEM cap handle\n");
    out.push_str("                        (setf (aref reply-caps 0) v)\n");
    out.push_str("                        (setf n-reply-caps 1)))))\n");
    out.push_str("                 ;; Error path\n");
    out.push_str(&format!(
        "                 (let ((err ({pkg_prefix}-result-error result)))\n"
    ));
    out.push_str("                   (setf (aref reply-payload 0) 0)   ; ok = false\n");
    out.push_str("                   (setf (aref reply-payload 4)\n");
    out.push_str("                         (if (slot-boundp err 'kind)\n");
    out.push_str("                             (let ((kw (slot-value err 'kind)))\n");
    out.push_str("                               (case kw\n");

    // Generate error discriminant mapping from enums
    if let Some(enums) = ast["enums"].as_array() {
        for e in enums {
            let variants = e["variants"].as_array().unwrap();
            for v in variants {
                let vname = v["name"].as_str().unwrap();
                let disc = v["discriminant"].as_i64().unwrap();
                out.push_str(&format!(
                    "                                 (:{} {disc})\n",
                    to_lisp_snake(vname)
                ));
            }
        }
    }
    out.push_str("                                 (otherwise 0))\n");
    out.push_str("                             0))))\n");
    out.push_str("             (values reply-payload reply-caps n-reply-caps)))))\n\n");

    // Dispatch by opcode
    out.push_str("    ;; ── Dispatch by opcode ──\n");
    out.push_str("    (ecase opcode\n");

    for m in methods {
        let mname = m["name"].as_str().unwrap();
        let const_name = format!("+op-{}+", to_lisp_snake(mname));
        let lisp_mname = format!("{pkg_prefix}-{mname}");
        let params = m["params"].as_array().unwrap();

        out.push_str(&format!("      (#{const_name}\n"));

        // Deserialize parameters from payload
        let mut deserialized_params = Vec::new();
        let mut offset = 0usize;
        let mut cap_index = 0usize;

        for p in params {
            let pname = p["name"].as_str().unwrap();
            let lisp_pname = to_lisp_snake(pname);
            let needs_cap = p["needs_cap"].as_bool().unwrap_or(false);
            let _wire_size = p["wire_size"].as_u64().unwrap_or(0);

            if needs_cap {
                // Arena parameter — cap handle from cap-slots
                deserialized_params.push(format!(
                    "({lisp_pname}-cap (aref cap-slots {cap_index}))"
                ));
                cap_index += 1;
                // Also get the count from payload
                let kind = p["ty"]["kind"].as_str().unwrap_or("array");
                if kind == "array" {
                    deserialized_params.push(format!(
                        "({lisp_pname}-count (sb-sys:sap-ref-32 (sb-sys:sap payload) {offset}))"
                    ));
                    offset += 4;
                }
            } else {
                let ty = &p["ty"];
                let kind = ty["kind"].as_str().unwrap_or("i32");
                match kind {
                    "i8" | "u8" | "bool" => {
                        deserialized_params.push(format!(
                            "({lisp_pname} (sb-sys:sap-ref-8 (sb-sys:sap payload) {offset}))"
                        ));
                        offset += 1;
                    }
                    "i16" | "u16" => {
                        deserialized_params.push(format!(
                            "({lisp_pname} (sb-sys:sap-ref-16 (sb-sys:sap payload) {offset}))"
                        ));
                        offset += 2;
                    }
                    "i32" | "u32" | "f32" => {
                        if kind == "f32" {
                            deserialized_params.push(format!(
                                "({lisp_pname} (sb-kernel:single-float-from-bits\n                       (sb-sys:sap-ref-32 (sb-sys:sap payload) {offset})))"
                            ));
                        } else {
                            deserialized_params.push(format!(
                                "({lisp_pname} (sb-sys:sap-ref-32 (sb-sys:sap payload) {offset}))"
                            ));
                        }
                        offset += 4;
                    }
                    "i64" | "u64" => {
                        deserialized_params.push(format!(
                            "({lisp_pname} (sb-sys:sap-ref-64 (sb-sys:sap payload) {offset}))"
                        ));
                        offset += 8;
                    }
                    "f64" => {
                        let off2 = offset + 4;
                        deserialized_params.push(format!(
                            "({lisp_pname} (sb-kernel:double-float-from-bits\n                       (sb-sys:sap-ref-32 (sb-sys:sap payload) {offset})\n                       (sb-sys:sap-ref-32 (sb-sys:sap payload) {off2})))"
                        ));
                        offset += 8;
                    }
                    "named" => {
                        // Struct — deserialize fields
                        let type_name = ty["name"].as_str().unwrap();
                        let struct_def = find_struct(ast, type_name);
                        if let Some(s) = struct_def {
                            let fields = s["fields"].as_array().unwrap();
                            let field_parts: Vec<String> = fields
                                .iter()
                                .map(|f| {
                                    let fname = f["name"].as_str().unwrap();
                                    let fkind = f["ty"]["kind"].as_str().unwrap_or("i32");
                                    let fwire = f["wire_size"].as_u64().unwrap_or(0);
                                    let ftype = fkind;
                                    let part = match ftype {
                                        "i32" | "u32" => format!(
                                            "(sb-sys:sap-ref-32 (sb-sys:sap payload) {offset})"
                                        ),
                                        "i64" | "u64" | "f64" => format!(
                                            "(sb-sys:sap-ref-64 (sb-sys:sap payload) {offset})"
                                        ),
                                        "named" => "0".into(), // nested struct TODO
                                        _ => "0".into(),
                                    };
                                    offset += fwire as usize;
                                    format!("({} {})", to_lisp_snake(fname), part)
                                })
                                .collect();
                            let lisp_type = to_lisp_snake(type_name);
                            deserialized_params.push(format!(
                                "({lisp_pname} (make-{lisp_type} {}))",
                                field_parts.join(" ")
                            ));
                        } else {
                            deserialized_params.push(format!("({lisp_pname} nil)"));
                        }
                    }
                    _ => {
                        deserialized_params.push(format!("({lisp_pname} 0)"));
                    }
                }
            }
        }

        if !deserialized_params.is_empty() {
            out.push_str("       (let* (");
            for (i, dp) in deserialized_params.iter().enumerate() {
                if i > 0 {
                    out.push_str("\n              ");
                }
                out.push_str(dp);
            }
            out.push_str(")\n");

            // Build call arguments
            let call_args: Vec<String> = params
                .iter()
                .map(|p| {
                    let pname = p["name"].as_str().unwrap();
                    let needs_cap = p["needs_cap"].as_bool().unwrap_or(false);
                    let lisp_pname = to_lisp_snake(pname);
                    if needs_cap {
                        format!("{lisp_pname}-cap {lisp_pname}-count")
                    } else {
                        lisp_pname
                    }
                })
                .collect();

            let is_async = m["is_async"].as_bool().unwrap_or(false);
            if is_async {
                out.push_str(&format!(
                    "         ;; Async: spawn a thread, acknowledge immediately\n"
                ));
                out.push_str("         (bt:make-thread\n");
                out.push_str(&format!(
                    "           (lambda () ({lisp_mname} {}))\n",
                    call_args.join(" ")
                ));
                out.push_str(&format!(
                    "           :name \"{lisp_mname}-worker\")\n"
                ));
                out.push_str(
                    "         (values (make-array 4 :element-type '(unsigned-byte 8)\n",
                );
                out.push_str(
                    "                                :initial-contents '(#x01 0 0 0))\n",
                );
                out.push_str(
                    "                 (make-array 8 :element-type '(unsigned-byte 16))\n",
                );
                out.push_str("                 0))\n");
            } else {
                out.push_str(&format!(
                    "         (encode-result ({lisp_mname} {})))\n",
                    call_args.join(" ")
                ));
            }
            out.push_str("       )\n");
        } else {
            // No parameters
            let is_async = m["is_async"].as_bool().unwrap_or(false);
            if is_async {
                out.push_str("       ;; Async: spawn a thread, acknowledge immediately\n");
                out.push_str("       (bt:make-thread\n");
                out.push_str(&format!(
                    "         (lambda () ({lisp_mname}))\n"
                ));
                out.push_str(&format!(
                    "         :name \"{lisp_mname}-worker\")\n"
                ));
                out.push_str(
                    "       (values (make-array 4 :element-type '(unsigned-byte 8)\n",
                );
                out.push_str(
                    "                              :initial-contents '(#x01 0 0 0))\n",
                );
                out.push_str(
                    "               (make-array 8 :element-type '(unsigned-byte 16))\n",
                );
                out.push_str("               0))\n");
            } else {
                out.push_str(&format!(
                    "       (encode-result ({lisp_mname})))\n"
                ));
            }
        }
    }

    out.push_str("    )))\n\n");
}

// ── Type helpers ────────────────────────────────────────────────────────────

fn find_struct<'a>(ast: &'a Value, name: &str) -> Option<&'a Value> {
    ast["structs"]
        .as_array()?
        .iter()
        .find(|s| s["name"].as_str() == Some(name))
}

/// Map IDL type JSON to Common Lisp type name for parameter declarations.
fn json_type_to_lisp_type(ty: &Value, _ast: &Value) -> String {
    let kind = ty["kind"].as_str().unwrap_or("i32");
    match kind {
        "i8" | "u8" => "(unsigned-byte 8)".into(),
        "i16" | "u16" => "(unsigned-byte 16)".into(),
        "i32" | "u32" => "(unsigned-byte 32)".into(),
        "i64" | "u64" => "(signed-byte 64)".into(),
        "f32" => "single-float".into(),
        "f64" => "double-float".into(),
        "bool" => "boolean".into(),
        "string" | "bytes" => "string".into(),
        "named" => {
            let name = ty["name"].as_str().unwrap_or("t");
            to_lisp_snake(name)
        }
        "array" => {
            // NOTE: the comment stays OUTSIDE the type string so the field's
            // closing paren is not swallowed by a `;` comment.
            "(unsigned-byte 16)".into()
        }
        "option" => "t".into(),
        "result" => "t".into(),
        "unit" => "null".into(),
        "map" => "(unsigned-byte 16)".into(),
        _ => "t".into(),
    }
}

/// Map IDL type JSON to Common Lisp type for param declarations (simpler form).
fn json_type_to_lisp_param_type(p: &Value, ast: &Value) -> String {
    let needs_cap = p["needs_cap"].as_bool().unwrap_or(false);
    if needs_cap {
        let kind = p["ty"]["kind"].as_str().unwrap_or("array");
        if kind == "array" {
            "(unsigned-byte 16)".into()
        } else {
            "(unsigned-byte 16)".into()
        }
    } else {
        json_type_to_lisp_type(&p["ty"], ast)
    }
}

/// Default value for a Lisp type.
fn lisp_type_default(ty: &Value) -> String {
    let kind = ty["kind"].as_str().unwrap_or("i32");
    match kind {
        "i8" | "u8" | "i16" | "u16" | "i32" | "u32" => "0".into(),
        "i64" | "u64" => "0".into(),
        "f32" => "0.0f0".into(),
        "f64" => "0.0d0".into(),
        "bool" => "nil".into(),
        "string" | "bytes" => "nil".into(),
        "named" => "nil".into(),
        "array" | "map" => "0".into(),
        _ => "nil".into(),
    }
}

fn to_lisp_name(ns: &str) -> String {
    ns.replace('.', "-")
}

fn to_lisp_package(ns: &str) -> String {
    // Convert "aerosls.calculator" to "calculator"
    ns.split('.').last().unwrap_or(ns).replace('-', ".")
}

fn to_lisp_snake(s: &str) -> String {
    let mut result = String::with_capacity(s.len() + 4);
    for (i, ch) in s.chars().enumerate() {
        if ch == '_' {
            result.push('-');
        } else if ch.is_uppercase() {
            if i > 0 {
                let prev = s.as_bytes()[i - 1] as char;
                if prev != '_' && prev.is_lowercase() {
                    result.push('-');
                }
            }
            result.push(ch.to_ascii_lowercase());
        } else {
            result.push(ch);
        }
    }
    result
}

fn collect_exports(ast: &Value) -> Vec<String> {
    let mut exports = Vec::new();
    if let Some(interfaces) = ast["interfaces"].as_array() {
        for iface in interfaces {
            let pkg_prefix = to_lisp_snake(iface["name"].as_str().unwrap());
            exports.push(format!("{pkg_prefix}-dispatch"));

            let methods = iface["methods"].as_array().map_or(&[] as &[Value], |v| v.as_slice());
            for m in methods {
                let mname = m["name"].as_str().unwrap();
                exports.push(format!("{}-{}", pkg_prefix, to_lisp_snake(mname)));
            }
        }
    }
    exports
}

// ── Tests ───────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn emit_calculator_lisp() {
        let src = include_str!("../../../idl/calculator.aeroidl");
        let doc = crate::parser::parse(src).expect("parse should succeed");
        let tc = crate::tycheck::type_check(&doc);
        let ast = crate::emit::emit_value(&doc, &tc);
        let lisp_code = emit_lisp(&ast);

        assert!(lisp_code.contains("(defpackage #:aerosls.calculator"));
        assert!(lisp_code.contains("(in-package #:aerosls.calculator)"));
        assert!(lisp_code.contains("(defconstant +op-add+"));
        assert!(lisp_code.contains("(defconstant +op-heavy-reduce+"));
        assert!(lisp_code.contains("(deftype calc-error-kind"));
        assert!(lisp_code.contains("(defstruct (vec2"));
        assert!(lisp_code.contains("(defstruct (matrix-data"));
        assert!(lisp_code.contains("(defun calculator-service-add"));
        assert!(lisp_code.contains("(defun calculator-service-div"));
        assert!(lisp_code.contains("(defun calculator-service-dot"));
        assert!(lisp_code.contains("(defun calculator-service-sqrt-batch"));
        assert!(lisp_code.contains("(defun calculator-service-heavy-reduce"));
        assert!(lisp_code.contains("(defun calculator-service-dispatch"));
        assert!(lisp_code.contains("(ecase opcode"));
        assert!(lisp_code.contains("(defun register-calculator-service"));
    }

    #[test]
    fn emit_logging_lisp() {
        let src = include_str!("../../../idl/logging.aeroidl");
        let doc = crate::parser::parse(src).expect("parse should succeed");
        let tc = crate::tycheck::type_check(&doc);
        let ast = crate::emit::emit_value(&doc, &tc);
        let lisp_code = emit_lisp(&ast);

        assert!(lisp_code.contains("(defpackage #:aerosls.logging"));
        assert!(lisp_code.contains("(defconstant +op-emit+"));
        assert!(lisp_code.contains("(defconstant +op-flush+"));
        assert!(lisp_code.contains("(deftype log-level"));
        assert!(lisp_code.contains("(defstruct (log-record"));
        assert!(lisp_code.contains("(defun logging-service-emit"));
        assert!(lisp_code.contains("(defun logging-service-flush"));
        assert!(lisp_code.contains("(defun logging-service-dispatch"));
    }

    #[test]
    fn emit_imageproc_lisp() {
        let src = include_str!("../../../idl/imageproc.aeroidl");
        let doc = crate::parser::parse(src).expect("parse should succeed");
        let tc = crate::tycheck::type_check(&doc);
        let ast = crate::emit::emit_value(&doc, &tc);
        let lisp_code = emit_lisp(&ast);

        assert!(lisp_code.contains("(defpackage #:aerosls.imageproc"));
        assert!(lisp_code.contains("(defconstant +op-blur+"));
        assert!(lisp_code.contains("(defstruct (image-descriptor"));
        assert!(lisp_code.contains("(defun image-processing-service-blur"));
        assert!(lisp_code.contains("(defun image-processing-service-dispatch"));
    }

    #[test]
    fn lisp_snake_case() {
        assert_eq!(to_lisp_snake("CalculatorService"), "calculator-service");
        assert_eq!(to_lisp_snake("ImageProcessingService"), "image-processing-service");
        assert_eq!(to_lisp_snake("Vec2"), "vec2");
        assert_eq!(to_lisp_snake("LogLevel"), "log-level");
        assert_eq!(to_lisp_snake("add"), "add");
    }

    #[test]
    fn lisp_package_name() {
        assert_eq!(to_lisp_package("aerosls.calculator"), "calculator");
        assert_eq!(to_lisp_package("aerosls.logging"), "logging");
        assert_eq!(to_lisp_package("aerosls.imageprocessing"), "imageprocessing");
    }
}
