//! Rust code generator — reads the typed AST JSON and emits a complete Rust
//! module with `#[repr(C)]` types and channel-based FFI stubs for cross-sidecar
//! calls.
//!
//! The generated module is self-contained: it declares enums, structs, a
//! `Result` wrapper, opcode constants, and `pub fn` stubs that serialize
//! arguments into channel messages, attach MEM caps for arena data, and block
//! on the reply.
//!
//! Usage:
//! ```text
//! aeroidl <input.aeroidl> --target rust        # emit to stdout
//! aeroidl <input.aeroidl> --target rust -o out.rs
//! ```

use serde_json::Value;

// ── Public API ──────────────────────────────────────────────────────────────

/// Emit a complete Rust module from the typed AST JSON.
pub fn emit_rust(ast: &Value) -> String {
    let mut out = String::with_capacity(8192);

    let namespace = ast["namespace"].as_str().unwrap_or("unknown");
    let version = ast["version"].as_str().unwrap_or("unknown");

    // Module header
    out.push_str(&format!("// Auto-generated by aeroidl-cc v0.1 — {namespace}\n"));
    out.push_str(&format!("// AeroIDL version: {version}\n"));
    out.push_str("//\n");
    out.push_str("// This module provides Rust FFI stubs for cross-sidecar calls.\n");
    out.push_str("// The sidecar runtime provides:\n");
    out.push_str("//   aerosls::chan_send(), aerosls::chan_recv(),\n");
    out.push_str("//   aerosls::arena_alloc(), aerosls::arena_free()\n");
    out.push_str("//\n");
    out.push_str("// Generated from the typed AST — do not edit manually.\n");
    out.push('\n');

    // Note: #![no_std] and extern crate alloc are not emitted here —
    // they belong in the consuming crate root, not in each generated module.
    out.push_str("use core::mem;\n\n");

    // ── Enums ────────────────────────────────────────────────────────────
    if let Some(enums) = ast["enums"].as_array() {
        for e in enums {
            emit_enum(&mut out, e);
        }
    }

    // ── Structs ──────────────────────────────────────────────────────────
    if let Some(structs) = ast["structs"].as_array() {
        for s in structs {
            emit_struct(&mut out, s);
        }
    }

    // ── Interfaces ───────────────────────────────────────────────────────
    if let Some(interfaces) = ast["interfaces"].as_array() {
        for iface in interfaces {
            emit_interface(&mut out, ast, iface, namespace);
        }
    }

    out
}

// ── Enum generation ─────────────────────────────────────────────────────────

fn emit_enum(out: &mut String, e: &Value) {
    let name = e["name"].as_str().unwrap();
    let variants = e["variants"].as_array().unwrap();

    out.push_str(&format!("/// {name} — AeroIDL enum (wire size: {} bytes)\n", e["wire_size"]));
    out.push_str("#[repr(u32)]\n");
    out.push_str("#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]\n");
    out.push_str(&format!("pub enum {name} {{\n"));
    for v in variants {
        let vname = v["name"].as_str().unwrap();
        let disc = v["discriminant"].as_i64().unwrap();
        out.push_str(&format!("    {vname} = {disc},\n"));
    }
    out.push_str("}\n\n");

    // Discriminant constants (for wire encoding/decoding)
    out.push_str(&format!("impl {name} {{\n"));
    out.push_str("    /// Convert from raw discriminant value.\n");
    out.push_str("    pub fn from_raw(v: u32) -> Option<Self> {\n");
    out.push_str("        match v {\n");
    for v in variants {
        let vname = v["name"].as_str().unwrap();
        let disc = v["discriminant"].as_i64().unwrap();
        out.push_str(&format!("            {disc} => Some({name}::{vname}),\n"));
    }
    out.push_str("            _ => None,\n");
    out.push_str("        }\n");
    out.push_str("    }\n\n");

    out.push_str("    /// Convert to raw discriminant value.\n");
    out.push_str("    pub fn to_raw(self) -> u32 {\n");
    out.push_str("        self as u32\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");
}

// ── Struct generation ───────────────────────────────────────────────────────

fn emit_struct(out: &mut String, s: &Value) {
    let name = s["name"].as_str().unwrap();
    let inline_size = s["inline_size"].as_u64().unwrap_or(0);
    let passed_as_cap = s["passed_as_cap"].as_bool().unwrap_or(false);
    let fields = s["fields"].as_array().unwrap();

    out.push_str(&format!(
        "/// {name} — AeroIDL struct (wire size: {inline_size} bytes{}\n",
        if passed_as_cap { ", passed as MEM cap" } else { "" }
    ));
    out.push_str("/// )\n");
    out.push_str("#[repr(C)]\n");
    out.push_str("#[derive(Clone, Copy, Debug)]\n");
    out.push_str(&format!("pub struct {name} {{\n"));
    for f in fields {
        let fname = f["name"].as_str().unwrap();
        let rty = json_type_to_rust(&f["ty"]);
        let comment = ownership_comment(&f["ownership"]);
        out.push_str(&format!("    pub {fname}: {rty},{comment}\n"));
    }
    out.push_str("}\n\n");

    // Wire-size constant
    out.push_str(&format!("impl {name} {{\n"));
    out.push_str(&format!("    pub const WIRE_SIZE: usize = {inline_size};\n"));
    out.push_str("}\n\n");
}

// ── Interface / method generation ───────────────────────────────────────────

fn emit_interface(out: &mut String, ast: &Value, iface: &Value, _namespace: &str) {
    let name = iface["name"].as_str().unwrap();
    let methods = iface["methods"].as_array().unwrap();
    let mod_name = to_snake_case(name);

    out.push_str(&format!("/// {name} — AeroIDL interface\n"));
    out.push_str(&format!("pub mod {mod_name} {{\n"));
    out.push_str("    use super::*;\n\n");

    // Opcode constants
    out.push_str("    /// Message opcodes for channel send/recv.\n");
    for m in methods {
        let mname = m["name"].as_str().unwrap();
        let opcode = m["opcode"].as_u64().unwrap();
        let const_name = format!("OP_{}", mname.to_uppercase());
        out.push_str(&format!("    pub const {const_name}: u16 = {opcode};\n"));
    }
    out.push('\n');

    // Channel handle (set during bootstrap)
    out.push_str("    /// Channel write endpoint (CHAN_W) to the remote sidecar.\n");
    out.push_str("    /// Set during bootstrap by the sidecar runtime.\n");
    out.push_str(&format!(
        "    pub static mut CHAN_W: u16 = 0xFFFF; /* CAP_NONE */\n\n"
    ));
    out.push_str("    /// Channel read endpoint (CHAN_R) from the remote sidecar.\n");
    out.push_str(&format!(
        "    pub static mut CHAN_R: u16 = 0xFFFF; /* CAP_NONE */\n\n"
    ));

    // Method stubs
    for m in methods {
        emit_method_stub(out, ast, m, &mod_name);
    }

    out.push_str("}\n\n");
}

fn emit_method_stub(out: &mut String, ast: &Value, m: &Value, _mod_name: &str) {
    let mname = m["name"].as_str().unwrap();
    let opcode = m["opcode"].as_u64().unwrap();
    let is_async = m["is_async"].as_bool().unwrap_or(false);
    let params = m["params"].as_array().unwrap();
    let return_type = &m["return_type"];
    let param_cap_count = m["param_cap_count"].as_u64().unwrap_or(0);

    // Build Rust function signature
    let mut sig_params = Vec::new();
    let mut needs_arena = false;
    for p in params {
        let pname = p["name"].as_str().unwrap();
        let rty = json_type_to_rust(&p["ty"]);
        sig_params.push(format!("{pname}: {rty}"));
        if p["needs_cap"].as_bool().unwrap_or(false) {
            needs_arena = true;
        }
    }

    // For arena params, also pass the cap handle and byte count
    if needs_arena {
        let arena_params: Vec<String> = params
            .iter()
            .filter(|p| p["needs_cap"].as_bool().unwrap_or(false))
            .map(|p| {
                let pname = p["name"].as_str().unwrap();
                format!("{pname}_cap: u16, {pname}_len: u32")
            })
            .collect();
        sig_params.extend(arena_params);
    }

    let _return_rty = json_type_to_rust(return_type);

    let const_name = format!("OP_{}", mname.to_uppercase());

    // Doc comment
    out.push_str(&format!("    /// `{mname}` — opcode {opcode}\n"));
    if is_async {
        out.push_str("    ///\n");
        out.push_str("    /// Async call: sends with NO_REPLY flag.\n");
        out.push_str("    /// The result is delivered later on a dedicated result channel.\n");
    }
    out.push_str("    ///\n");
    out.push_str("    /// # Wire format\n");
    out.push_str(&format!(
        "    ///   SEND_CAP {{ opcode={opcode}, payload=[...], caps=[...] }}\n"
    ));
    if !is_async {
        out.push_str(&format!(
            "    ///   RECV_CAP {{ payload=[AeroidlResult], caps=[...] }}\n"
        ));
    }
    out.push('\n');

    if is_async {
        // Async: fire-and-forget, returns () (ack received immediately)
        out.push_str(&format!(
            "    pub fn {mname}({}) -> Result<(), AEROIDL_ERROR> {{\n",
            sig_params.join(", ")
        ));
    } else {
        // For Result<T, E> return types, the stub returns Result<T, AEROIDL_ERROR>
        let ret = json_type_to_rust(return_type);
        let is_result = return_type["kind"].as_str() == Some("result");
        // json_type_to_rust already wraps Result<T,E> as AeroidlResult<T>,
        // so we use it directly for result return types.
        let sig_ret = if is_result {
            ret
        } else {
            format!("AeroidlResult<{ret}>")
        };
        out.push_str(&format!(
            "    pub fn {mname}({}) -> {sig_ret} {{\n",
            sig_params.join(", ")
        ));
    }

    // Body: serialize, send, recv, deserialize
    out.push_str("        // ── Step 1: build request payload ──\n");

    // Calculate total payload size
    let payload_size = calculate_payload_size(params, return_type);
    if payload_size > 0 {
        out.push_str(&format!("        let mut payload = [0u8; {payload_size}];\n"));
        emit_serialize_params(out, ast, params, "        ");
    } else {
        out.push_str("        let payload: [u8; 0] = [];\n");
    }

    out.push('\n');
    out.push_str("        // ── Step 2: send request ──\n");
    if is_async {
        out.push_str("        let flags = CHAN_FLAG_NO_REPLY;\n");
    } else {
        out.push_str(&format!("        let flags: u16 = 0;\n"));
    }

    if param_cap_count > 0 {
        out.push_str(&format!(
            "        let cap_descs = [\n"
        ));
        for p in params {
            if p["needs_cap"].as_bool().unwrap_or(false) {
                let pname = p["name"].as_str().unwrap();
                let ownership = p["ownership"].as_str().unwrap_or("borrowed");
                // Encode the IDL ownership annotation into the cap descriptor
                // flags (same mapping as the C generator): BORROWED keeps the
                // caller's slot, ARENA_OWNED transfers it to the callee.
                let (perm, flag) = match ownership {
                    "arena" => ("CAP_PERM_R | CAP_PERM_W", "CAP_FLAG_ARENA"),
                    "owned" => ("CAP_PERM_R | CAP_PERM_W", "CAP_FLAG_ARENA_OWNED"),
                    _ => ("CAP_PERM_R", "CAP_FLAG_BORROWED"),
                };
                out.push_str(&format!(
                    "            CapDescriptor {{ slot: {pname}_cap as u32, offset: 0, len: {pname}_len, rights: {perm}, flags: {flag}, pad: 0 }},\n"
                ));
            }
        }
        out.push_str("        ];\n");
    }

    if param_cap_count > 0 {
        out.push_str("        let n_caps_send: u32 = cap_descs.len() as u32;\n");
    }
    out.push_str("        unsafe {\n");
    out.push_str("            let _rc = chan_send(\n");
    out.push_str("                CHAN_W,\n");
    out.push_str(&format!("                {const_name},\n"));
    out.push_str("                payload.as_ptr(),\n");
    out.push_str("                payload.len() as u32,\n");
    if param_cap_count > 0 {
        out.push_str("                cap_descs.as_ptr(),\n");
        out.push_str("                n_caps_send,\n");
    } else {
        out.push_str("                core::ptr::null(),\n");
        out.push_str("                0,\n");
    }
    out.push_str("                flags,\n");
    out.push_str("            );\n");
    out.push_str("            if _rc != 0 {\n");
    out.push_str("                return Err(AEROIDL_ERROR { code: _rc as u32, message: alloc::string::String::from(\"chan_send failed\") });\n");
    out.push_str("            }\n");
    out.push_str("        }\n");

    if is_async {
        out.push_str("        Ok(())\n");
    } else {
        // Step 3: receive reply
        out.push('\n');
        out.push_str("        // ── Step 3: receive reply ──\n");
        let reply_size = calculate_reply_size(return_type);
        out.push_str(&format!("        let mut reply_buf = [0u8; {reply_size}];\n"));
        out.push_str("        let mut cap_slots = [0u16; 8];\n");
        out.push_str("        let mut n_caps: u16 = 0;\n");
        out.push_str("        unsafe {\n");
        out.push_str("            let _rc = chan_recv(\n");
        out.push_str("                CHAN_R,\n");
        out.push_str("                reply_buf.as_mut_ptr(),\n");
        out.push_str("                reply_buf.len() as u32,\n");
        out.push_str("                cap_slots.as_mut_ptr(),\n");
        out.push_str("                &mut n_caps as *mut u16,\n");
        out.push_str("            );\n");
        out.push_str("            if _rc != 0 {\n");
        out.push_str("                return Err(AEROIDL_ERROR { code: _rc as u32, message: alloc::string::String::from(\"chan_recv failed\") });\n");
        out.push_str("            }\n");
        out.push_str("        }\n");

        // Step 4: deserialize reply
        out.push('\n');
        out.push_str("        // ── Step 4: deserialize reply ──\n");
        emit_deserialize_reply(out, ast, return_type, "        ");
    }

    out.push_str("    }\n\n");
}

// ── Serialization helpers ───────────────────────────────────────────────────

fn emit_serialize_params(out: &mut String, ast: &Value, params: &[Value], indent: &str) {
    let mut offset = 0usize;
    for p in params {
        if p["needs_cap"].as_bool().unwrap_or(false) {
            // Arena params: only the count/metadata goes in the payload,
            // the actual data goes via the cap descriptor.
            let pname = p["name"].as_str().unwrap();
            let rty = &p["ty"];
            if rty["kind"].as_str() == Some("array") {
                out.push_str(&format!(
                    "{indent}payload[{offset}..{offset}+4].copy_from_slice(&{pname}_len.to_le_bytes());\n"
                ));
                offset += 4;
            }
        } else {
            let pname = p["name"].as_str().unwrap();
            let wire_size = p["wire_size"].as_u64().unwrap_or(0) as usize;
            emit_serialize_value(out, ast, pname, &p["ty"], offset, indent);
            offset += wire_size;
        }
    }
}

fn emit_serialize_value(out: &mut String, ast: &Value, var_name: &str, ty: &Value, offset: usize, indent: &str) {
    let kind = ty["kind"].as_str().unwrap_or("i32");
    match kind {
        "i8" => {
            out.push_str(&format!(
                "{indent}payload[{offset}] = {var_name} as u8;\n"
            ));
        }
        "i16" | "u16" => {
            out.push_str(&format!(
                "{indent}payload[{offset}..{offset}+2].copy_from_slice(&({var_name} as u16).to_le_bytes());\n"
            ));
        }
        "i32" | "u32" | "f32" | "bool" => {
            out.push_str(&format!(
                "{indent}payload[{offset}..{offset}+4].copy_from_slice(&({var_name} as u32).to_le_bytes());\n"
            ));
        }
        "i64" | "u64" | "f64" => {
            out.push_str(&format!(
                "{indent}payload[{offset}..{offset}+8].copy_from_slice(&({var_name} as u64).to_le_bytes());\n"
            ));
        }
        "named" => {
            let type_name = ty["name"].as_str().unwrap_or("Unknown");
            let fields = get_struct_field_names(ast, type_name);
            if !fields.is_empty() {
                let mut inner_offset = offset;
                for f in &fields {
                    let fname = f["name"].as_str().unwrap_or("_");
                    let field_var = format!("{var_name}.{fname}");
                    emit_serialize_value(out, ast, &field_var, &f["ty"], inner_offset, indent);
                    inner_offset += get_wire_size(&f["ty"]) as usize;
                }
            }
        }
        "unit" => { /* 0 bytes, nothing to serialize */ }
        _ => {
            out.push_str(&format!(
                "{indent}// TODO: serialize {kind} at offset {offset}\n"
            ));
        }
    }
}

fn emit_deserialize_reply(out: &mut String, ast: &Value, return_type: &Value, indent: &str) {
    let kind = return_type["kind"].as_str().unwrap_or("unit");
    match kind {
        "unit" => {
            out.push_str(&format!("{indent}Ok(())\n"));
        }
        "result" => {
            let ok_type = return_type.get("inner").unwrap();
            let err_type = return_type.get("inner2");

            out.push_str(&format!("{indent}let ok_byte = reply_buf[0];\n"));
            out.push_str(&format!("{indent}if ok_byte == 1 {{\n"));

            let ok_kind = ok_type["kind"].as_str().unwrap_or("unit");
            match ok_kind {
                "unit" => {
                    out.push_str(&format!("{indent}    Ok(())\n"));
                }
                "i32" => {
                    out.push_str(&format!(
                        "{indent}    let val = i32::from_le_bytes(reply_buf[4..8].try_into().unwrap());\n"
                    ));
                    out.push_str(&format!("{indent}    Ok(val)\n"));
                }
                "i64" => {
                    out.push_str(&format!(
                        "{indent}    let val = i64::from_le_bytes(reply_buf[8..16].try_into().unwrap());\n"
                    ));
                    out.push_str(&format!("{indent}    Ok(val)\n"));
                }
                "u32" => {
                    out.push_str(&format!(
                        "{indent}    let val = u32::from_le_bytes(reply_buf[4..8].try_into().unwrap());\n"
                    ));
                    out.push_str(&format!("{indent}    Ok(val)\n"));
                }
                "f64" => {
                    out.push_str(&format!(
                        "{indent}    let val = f64::from_le_bytes(reply_buf[8..16].try_into().unwrap());\n"
                    ));
                    out.push_str(&format!("{indent}    Ok(val)\n"));
                }
                "named" => {
                    let type_name = ok_type["name"].as_str().unwrap_or("Unknown");
                    let fields = get_struct_field_names(ast, type_name);
                    if !fields.is_empty() {
                        let mut inner_offset = 8; // after ok byte + padding
                        out.push_str(&format!(
                            "{indent}    // Deserialize {type_name} from reply payload\n"
                        ));
                        for f in &fields {
                            let fname = f["name"].as_str().unwrap_or("_");
                            let field_kind = f["ty"]["kind"].as_str().unwrap_or("i32");
                            let ws = get_wire_size(&f["ty"]);
                            match field_kind {
                                "i32" | "u32" | "f32" => {
                                    out.push_str(&format!(
                                        "{indent}    let {fname} = u32::from_le_bytes(reply_buf[{inner_offset}..{inner_offset}+4].try_into().unwrap());\n"
                                    ));
                                }
                                "i64" | "u64" | "f64" => {
                                    out.push_str(&format!(
                                        "{indent}    let {fname} = u64::from_le_bytes(reply_buf[{inner_offset}..{inner_offset}+8].try_into().unwrap());\n"
                                    ));
                                }
                                "named" => {
                                    let nested_name = f["ty"]["name"].as_str().unwrap_or("_");
                                    // Enums deserialize via from_raw; structs keep the TODO.
                                    if is_enum_type(ast, nested_name) {
                                        let first = enum_first_variant(ast, nested_name)
                                            .unwrap_or_else(|| "UNKNOWN".into());
                                        out.push_str(&format!(
                                            "{indent}    let {fname} = {nested_name}::from_raw(u32::from_le_bytes(reply_buf[{inner_offset}..{inner_offset}+4].try_into().unwrap())).unwrap_or({nested_name}::{first});\n"
                                        ));
                                    } else {
                                        out.push_str(&format!(
                                            "{indent}    let {fname} = 0; // TODO: deserialize nested {field_kind}\n"
                                        ));
                                    }
                                }
                                "string" | "bytes" => {
                                    out.push_str(&format!(
                                        "{indent}    let {fname} = cap_slots[0]; // MEM cap handle\n"
                                    ));
                                }
                                _ => {
                                    out.push_str(&format!(
                                        "{indent}    let {fname} = 0; // TODO: deserialize {field_kind}\n"
                                    ));
                                }
                            }
                            inner_offset += ws as usize;
                        }
                        // Enum fields are already typed via from_raw — no `as` cast.
                        let field_exprs: Vec<String> = fields
                            .iter()
                            .map(|f| {
                                let fname = f["name"].as_str().unwrap_or("_");
                                let is_enum = f["ty"]["kind"].as_str() == Some("named")
                                    && is_enum_type(ast, f["ty"]["name"].as_str().unwrap_or("_"));
                                if is_enum {
                                    format!("{fname}: {fname}")
                                } else {
                                    format!("{fname}: {fname} as _")
                                }
                            })
                            .collect();
                        out.push_str(&format!(
                            "{indent}    Ok({type_name} {{ {} }})\n",
                            field_exprs.join(", ")
                        ));
                    } else {
                        out.push_str(&format!(
                            "{indent}    // TODO: deserialize {type_name}\n"
                        ));
                        out.push_str(&format!("{indent}    core::unimplemented!()\n"));
                    }
                }
                "array" => {
                    out.push_str(&format!(
                        "{indent}    // Arena cap handle is in cap_slots[0], count in reply_buf[4..8]\n"
                    ));
                    out.push_str(&format!(
                        "{indent}    let count = u32::from_le_bytes(reply_buf[4..8].try_into().unwrap());\n"
                    ));
                    out.push_str(&format!(
                        "{indent}    Ok(ArenaSlice::new(cap_slots[0], count))\n"
                    ));
                }
                _ => {
                    out.push_str(&format!(
                        "{indent}    // TODO: deserialize {ok_kind}\n"
                    ));
                    out.push_str(&format!("{indent}    core::unimplemented!()\n"));
                }
            }

            out.push_str(&format!("{indent}}} else {{\n"));
            // Error path
            if let Some(err_type) = err_type {
                let err_kind = err_type["kind"].as_str().unwrap_or("unit");
                match err_kind {
                    "named" => {

                        out.push_str(&format!(
                            "{indent}    let code = u32::from_le_bytes(reply_buf[4..8].try_into().unwrap());\n"
                        ));
                        out.push_str(&format!(
                            "{indent}    Err(AEROIDL_ERROR {{ code, message: alloc::string::String::new() }})\n"
                        ));
                    }
                    "string" => {
                        out.push_str(&format!(
                            "{indent}    let msg = alloc::string::String::from_utf8_lossy(&reply_buf[4..]).into_owned();\n"
                        ));
                        out.push_str(&format!(
                            "{indent}    Err(AEROIDL_ERROR {{ code: 0, message: msg }})\n"
                        ));
                    }
                    _ => {
                        out.push_str(&format!(
                            "{indent}    Err(AEROIDL_ERROR {{ code: 0, message: alloc::string::String::new() }})\n"
                        ));
                    }
                }
            } else {
                out.push_str(&format!(
                    "{indent}    Err(AEROIDL_ERROR {{ code: 0, message: alloc::string::String::new() }})\n"
                ));
            }
            out.push_str(&format!("{indent}}}\n"));
        }
        "named" => {
            let type_name = return_type["name"].as_str().unwrap_or("Unknown");
            let fields = get_struct_field_names(ast, type_name);
            if !fields.is_empty() {
                let mut inner_offset = 8;
                for f in &fields {
                    let fname = f["name"].as_str().unwrap_or("_");
                    emit_serialize_value(
                        out,
                        ast,
                        fname,
                        &f["ty"],
                        inner_offset,
                        indent,
                    );
                    inner_offset += get_wire_size(&f["ty"]) as usize;
                }
            }
            out.push_str(&format!(
                "{indent}// TODO: deserialize {type_name}\n"
            ));
            out.push_str(&format!("{indent}core::unimplemented!()\n"));
        }
        _ => {
            out.push_str(&format!(
                "{indent}// TODO: deserialize {kind}\n"
            ));
            out.push_str(&format!("{indent}core::unimplemented!()\n"));
        }
    }
}

// ── Type helpers ────────────────────────────────────────────────────────────

/// Map an IDL type JSON to a Rust type string.
fn json_type_to_rust(ty: &Value) -> String {
    let kind = ty["kind"].as_str().unwrap_or("i32");
    match kind {
        "i8" => "i8".into(),
        "i16" => "i16".into(),
        "i32" => "i32".into(),
        "i64" => "i64".into(),
        "u8" => "u8".into(),
        "u16" => "u16".into(),
        "u32" => "u32".into(),
        "u64" => "u64".into(),
        "f32" => "f32".into(),
        "f64" => "f64".into(),
        "bool" => "bool".into(),
        "string" => "u16 /* cap handle */".into(),
        "bytes" => "u16 /* cap handle */".into(),
        "named" => ty["name"].as_str().unwrap_or("Unknown").into(),
        "array" => {
            let inner = ty.get("inner").map(|i| json_type_to_rust(i)).unwrap_or_default();
            format!("ArenaSlice<{inner}>")
        }
        "option" => {
            let inner = ty.get("inner").map(|i| json_type_to_rust(i)).unwrap_or_default();
            format!("Option<{inner}>")
        }
        "result" => {
            let ok = ty.get("inner").map(|i| json_type_to_rust(i)).unwrap_or("()".into());
            format!("AeroidlResult<{ok}>")
        }
        "unit" => "()".into(),
        "map" => "u16 /* cap handle */".into(),
        _ => "u64 /* unknown */".into(),
    }
}

fn ownership_comment(ownership: &Value) -> String {
    match ownership.as_str().unwrap_or("inline") {
        "borrowed" => " /* @borrowed */".into(),
        "owned" => " /* @owned */".into(),
        "arena" => " /* @arena */".into(),
        _ => String::new(),
    }
}

fn to_snake_case(s: &str) -> String {
    let mut result = String::with_capacity(s.len() + 4);
    for (i, ch) in s.chars().enumerate() {
        if ch.is_uppercase() {
            if i > 0 {
                result.push('_');
            }
            result.push(ch.to_ascii_lowercase());
        } else {
            result.push(ch);
        }
    }
    result
}

/// Calculate the payload size for a method request.
fn calculate_payload_size(params: &[Value], _return_type: &Value) -> usize {
    let mut size = 0usize;
    for p in params {
        if p["needs_cap"].as_bool().unwrap_or(false) {
            // Arena params: only the count/metadata goes in the payload
            let kind = p["ty"]["kind"].as_str().unwrap_or("array");
            if kind == "array" {
                size += 4; // count as u32
            } else {
                size += 8; // generic cap metadata
            }
        } else {
            size += p["wire_size"].as_u64().unwrap_or(0) as usize;
        }
    }
    size
}

/// Calculate the reply buffer size.
fn calculate_reply_size(return_type: &Value) -> usize {
    let kind = return_type["kind"].as_str().unwrap_or("unit");
    match kind {
        "unit" => 1, // just ok byte
        "result" => {
            // ok byte + max(ok_size, err_size) — simplified to 32 bytes
            32
        }
        "named" => 32,
        _ => 32,
    }
}

/// Look up a struct definition by name from the AST.
fn find_struct<'a>(ast: &'a Value, name: &str) -> Option<&'a Value> {
    ast["structs"].as_array()?.iter().find(|s| s["name"].as_str() == Some(name))
}

/// True if `name` refers to an enum type in the AST.
fn is_enum_type(ast: &Value, name: &str) -> bool {
    ast["enums"]
        .as_array()
        .map(|es| es.iter().any(|e| e["name"].as_str() == Some(name)))
        .unwrap_or(false)
}

/// Name of the first variant of an enum (used as a `from_raw` fallback).
fn enum_first_variant(ast: &Value, name: &str) -> Option<String> {
    ast["enums"]
        .as_array()?
        .iter()
        .find(|e| e["name"].as_str() == Some(name))?
        .get("variants")?
        .as_array()?
        .first()?
        .get("name")?
        .as_str()
        .map(|s| s.to_string())
}

/// Get struct field names from the AST.
fn get_struct_field_names(ast: &Value, type_name: &str) -> Vec<Value> {
    find_struct(ast, type_name)
        .and_then(|s| s["fields"].as_array())
        .cloned()
        .unwrap_or_default()
}

fn get_wire_size(ty: &Value) -> u64 {
    let kind = ty["kind"].as_str().unwrap_or("i32");
    match kind {
        "i8" | "u8" | "bool" => 1,
        "i16" | "u16" => 2,
        "i32" | "u32" | "f32" => 4,
        "i64" | "u64" | "f64" => 8,
        "string" | "bytes" | "array" | "map" => 8,
        _ => 8,
    }
}

// ── Common types ────────────────────────────────────────────────────────────

/// Emit common type definitions used by all generated code.
pub fn emit_common_types() -> String {
    r#"
// ═══════════════════════════════════════════════════════════════════════════
// Common types — shared by all generated AeroIDL modules
// ═══════════════════════════════════════════════════════════════════════════

/// Error type for AeroIDL cross-sidecar calls.
#[derive(Clone, Debug)]
pub struct AEROIDL_ERROR {
    pub code: u32,
    pub message: alloc::string::String,
}

impl core::fmt::Display for AEROIDL_ERROR {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        write!(f, "AeroIDL error {}: {}", self.code, self.message)
    }
}

/// Result type for AeroIDL cross-sidecar calls.
pub type AeroidlResult<T> = Result<T, AEROIDL_ERROR>;

/// A slice referencing arena-allocated data via a MEM cap handle.
/// The cap handle points into the shared arena visible to both sidecars.
#[derive(Clone, Copy, Debug)]
pub struct ArenaSlice<T> {
    pub cap: u16,
    pub len: u32,
    _marker: core::marker::PhantomData<T>,
}

impl<T> ArenaSlice<T> {
    pub fn new(cap: u16, len: u32) -> Self {
        Self {
            cap,
            len,
            _marker: core::marker::PhantomData,
        }
    }

    /// Get the cap handle.
    pub fn cap_handle(self) -> u16 {
        self.cap
    }

    /// Get the element count (for fixed-size T).
    pub fn len(self) -> u32 {
        self.len
    }
}

/// Capability argument descriptor (16 bytes, matching kernel cap.h layout).
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct CapDescriptor {
    pub slot: u32,
    pub offset: u32,
    pub len: u32,
    pub rights: u8,
    pub flags: u8,
    pub pad: u16,
}

// Permission constants (matching cap.h)
pub const CAP_PERM_R: u8 = 0x01;
pub const CAP_PERM_W: u8 = 0x02;

// Capability ownership flags (matching user/libaerocap/aerosls_cap.h
// AEROSLS_CAP_FLAG_*): BORROWED = caller retains ownership, ARENA = shared
// arena slot, ARENA_OWNED = ownership transfers to the callee on send.
pub const CAP_FLAG_BORROWED: u8 = 0x00;
pub const CAP_FLAG_ARENA: u8 = 0x01;
pub const CAP_FLAG_ARENA_OWNED: u8 = 0x02;

// Channel flag constants — kernel message flags (kernel/cap.h ChanMsg.flags,
// bit0 = NO_REPLY). MUST match user/libaerocap/aerosls_cap.h's
// AEROSLS_CHAN_FLAG_NO_REPLY and the runtime's req::CHAN_FLAG_NO_REPLY.
pub const CHAN_FLAG_NO_REPLY: u16 = 0x0001;

// Capability sentinel
pub const CAP_NONE: u16 = 0xFFFF;

// ═══════════════════════════════════════════════════════════════════════════
// Sidecar runtime FFI — provided by the sidecar SDK (linked separately)
// ═══════════════════════════════════════════════════════════════════════════

extern "C" {
    /// Send a message on a channel with optional capability descriptors.
    pub fn chan_send(
        chan_w: u16,
        opcode: u16,
        payload: *const u8,
        payload_len: u32,
        caps: *const CapDescriptor,
        n_caps: u32,
        flags: u16,
    ) -> i32;

    /// Receive a message from a channel.
    pub fn chan_recv(
        chan_r: u16,
        buf: *mut u8,
        buf_len: u32,
        cap_slots: *mut u16,
        n_slots: *mut u16,
    ) -> i32;

    /// Allocate a buffer from the shared arena.
    pub fn arena_alloc(size: u32, perm: u8) -> u16;

    /// Free an arena buffer.
    pub fn arena_free(cap: u16);

    /// Get the raw pointer for an arena buffer (for zero-copy access).
    pub fn arena_mem(cap: u16) -> *mut u8;

    /// Get the next request ID (monotonically incrementing).
    pub fn next_request_id() -> u32;
}
"#
    .into()
}

// ── Tests ───────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn emit_calculator_rust() {
        let src = include_str!("../../../idl/calculator.aeroidl");
        let doc = crate::parser::parse(src).expect("parse should succeed");
        let tc = crate::tycheck::type_check(&doc);
        let ast = crate::emit::emit_value(&doc, &tc);
        let rust_code = emit_rust(&ast);

        assert!(rust_code.contains("pub enum CalcErrorKind"));
        assert!(rust_code.contains("DIVISION_BY_ZERO = 1"));
        assert!(rust_code.contains("pub struct Vec2"));
        assert!(rust_code.contains("pub struct MatrixData"));
        assert!(rust_code.contains("pub mod calculator_service"));
        assert!(rust_code.contains("pub const OP_ADD: u16 = 1"));
        assert!(rust_code.contains("pub fn add("));
        assert!(rust_code.contains("pub fn div("));
        assert!(rust_code.contains("pub fn dot("));
        assert!(rust_code.contains("pub fn sqrt_batch("));
        assert!(rust_code.contains("pub fn heavy_reduce("));
        assert!(rust_code.contains("OP_HEAVY_REDUCE: u16 = 6"));
    }

    #[test]
    fn emit_logging_rust() {
        let src = include_str!("../../../idl/logging.aeroidl");
        let doc = crate::parser::parse(src).expect("parse should succeed");
        let tc = crate::tycheck::type_check(&doc);
        let ast = crate::emit::emit_value(&doc, &tc);
        let rust_code = emit_rust(&ast);

        assert!(rust_code.contains("pub enum LogLevel"));
        assert!(rust_code.contains("pub struct LogRecord"));
        assert!(rust_code.contains("pub mod logging_service"));
        assert!(rust_code.contains("pub fn emit("));
        assert!(rust_code.contains("pub fn flush("));
    }

    #[test]
    fn emit_imageproc_rust() {
        let src = include_str!("../../../idl/imageproc.aeroidl");
        let doc = crate::parser::parse(src).expect("parse should succeed");
        let tc = crate::tycheck::type_check(&doc);
        let ast = crate::emit::emit_value(&doc, &tc);
        let rust_code = emit_rust(&ast);

        assert!(rust_code.contains("pub enum PixelFormat"));
        assert!(rust_code.contains("pub struct ImageDescriptor"));
        assert!(rust_code.contains("pub mod image_processing_service"));
        assert!(rust_code.contains("pub fn blur("));
        assert!(rust_code.contains("pub fn resize_inplace("));
        assert!(rust_code.contains("pub fn histogram("));
        assert!(rust_code.contains("pub fn composite("));
    }

    #[test]
    fn to_snake_case_test() {
        assert_eq!(to_snake_case("CalculatorService"), "calculator_service");
        assert_eq!(to_snake_case("ImageProcessingService"), "image_processing_service");
        assert_eq!(to_snake_case("Vec2"), "vec2");
        assert_eq!(to_snake_case("LogLevel"), "log_level");
    }

    #[test]
    fn common_types_present() {
        let common = emit_common_types();
        assert!(common.contains("AEROIDL_ERROR"));
        assert!(common.contains("AeroidlResult"));
        assert!(common.contains("ArenaSlice"));
        assert!(common.contains("CapDescriptor"));
        assert!(common.contains("fn chan_send("));
        assert!(common.contains("fn arena_alloc("));
    }
}
