//! C code generator — reads the typed AST JSON and emits a complete C header
//! with `static inline` stub functions, type definitions, and a dispatch table
//! matching the pattern in `gen/calculator.h`.
//!
//! Usage:
//! ```text
//! aeroidl <input.aeroidl> --target c          # emit to stdout
//! aeroidl <input.aeroidl> --target c -o out.h
//! ```

use serde_json::Value;

// ── Public API ──────────────────────────────────────────────────────────────

/// Emit a complete C header from the typed AST JSON.
pub fn emit_c(ast: &Value) -> String {
    let mut out = String::with_capacity(8192);

    let namespace = ast["namespace"].as_str().unwrap_or("unknown");
    let version = ast["version"].as_str().unwrap_or("unknown");
    let mod_name = to_c_name(namespace);
    let guard = format!("AEROSLS_{}_H", mod_name.to_uppercase());

    // ── Header guard + preamble ─────────────────────────────────────────
    out.push_str("/**\n");
    out.push_str(&format!(" * {mod_name}.h — Auto-generated by aeroidl-cc v0.1\n"));
    out.push_str(&format!(" * AeroIDL version: {version}\n"));
    out.push_str(" *\n");
    out.push_str(" * This header provides C stubs for cross-sidecar calls.\n");
    out.push_str(" * The sidecar runtime (linked separately) provides:\n");
    out.push_str(" *   aerosls_chan_send(), aerosls_chan_recv(),\n");
    out.push_str(" *   aerosls_arena_alloc(), aerosls_arena_free(),\n");
    out.push_str(" *   aerosls_next_request_id()\n");
    out.push_str(" *\n");
    out.push_str(" * Generated from the typed AST — do not edit manually.\n");
    out.push_str(" */\n");
    out.push_str(&format!("#ifndef {guard}\n"));
    out.push_str(&format!("#define {guard}\n\n"));
    out.push_str("#include <stdint.h>\n");
    out.push_str("#include <stddef.h>\n");
    out.push_str("#include <aerosls_cap.h>\n\n");
    out.push_str("#ifdef __cplusplus\n");
    out.push_str("extern \"C\" {\n");
    out.push_str("#endif\n\n");

    // ── Build enum-to-prefix mapping from interfaces ────────────────────
    let mut enum_prefix_map: std::collections::HashMap<String, String> = std::collections::HashMap::new();
    if let Some(interfaces) = ast["interfaces"].as_array() {
        for iface in interfaces {
            let iface_name = iface["name"].as_str().unwrap();
            let prefix = to_c_prefix(iface_name);
            // Scan all method signatures for enum types (direct and via structs)
            if let Some(methods) = iface["methods"].as_array() {
                for m in methods {
                    // Direct enums in return type
                    collect_enum_names(ast, &m["return_type"], &mut |name| {
                        enum_prefix_map.entry(name).or_insert_with(|| prefix.clone());
                    });
                    // Enums in param types
                    if let Some(params_arr) = m["params"].as_array() {
                        for p in params_arr {
                            collect_enum_names(ast, &p["ty"], &mut |name| {
                                enum_prefix_map.entry(name).or_insert_with(|| prefix.clone());
                            });
                        }
                    }
                    // Enums in structs used by params and return type
                    scan_struct_refs_for_enums(ast, &[m["return_type"].clone()], &prefix, &mut enum_prefix_map);
                    if let Some(params_arr) = m["params"].as_array() {
                        scan_struct_refs_for_enums(ast, params_arr, &prefix, &mut enum_prefix_map);
                    }
                }
            }
        }
    }
    // Fallback: first interface's prefix
    let default_prefix = ast["interfaces"].as_array()
        .and_then(|ifaces| ifaces.first())
        .map(|i| to_c_prefix(i["name"].as_str().unwrap_or("")))
        .unwrap_or_else(|| "AERO".into());

    // ── Enums ───────────────────────────────────────────────────────────
    if let Some(enums) = ast["enums"].as_array() {
        if !enums.is_empty() {
            out.push_str("/* ─── Generated enums ─────────────────────────────────────────────────────── */\n\n");
            for e in enums {
                let ename = e["name"].as_str().unwrap();
                let prefix = enum_prefix_map.get(ename).unwrap_or(&default_prefix);
                emit_enum(&mut out, e, prefix);
            }
        }
    }

    // ── Structs ─────────────────────────────────────────────────────────
    if let Some(structs) = ast["structs"].as_array() {
        if !structs.is_empty() {
            out.push_str("/* ─── Generated structs ───────────────────────────────────────────────────── */\n\n");
            for s in structs {
                emit_struct(&mut out, s, ast, &mod_name);
            }
        }
    }

    // ── Interfaces ──────────────────────────────────────────────────────
    if let Some(interfaces) = ast["interfaces"].as_array() {
        for iface in interfaces {
            emit_interface(&mut out, ast, iface, &mod_name);
        }
    }

    // ── Arena helpers ───────────────────────────────────────────────────
    emit_arena_helpers(&mut out, &mod_name);

    // ── Footer ──────────────────────────────────────────────────────────
    out.push_str("#ifdef __cplusplus\n");
    out.push_str("}\n");
    out.push_str("#endif\n\n");
    out.push_str(&format!("#endif /* {guard} */\n"));

    out
}

// ── Enum generation ─────────────────────────────────────────────────────────

fn emit_enum(out: &mut String, e: &Value, prefix: &str) {
    let name = e["name"].as_str().unwrap();
    let variants = e["variants"].as_array().unwrap();
    // Enum name abbreviation: CalcErrorKind -> ERROR, LogLevel -> LEVEL
    let tag = enum_tag(name);

    out.push_str(&format!("typedef enum {{\n"));
    for v in variants {
        let vname = v["name"].as_str().unwrap();
        let disc = v["discriminant"].as_i64().unwrap();
        out.push_str(&format!(
            "    {prefix}_{tag}_{vname} = {disc},\n"
        ));
    }
    out.push_str(&format!("}} {name};\n\n"));
}

// ── Struct generation ───────────────────────────────────────────────────────

fn emit_struct(out: &mut String, s: &Value, ast: &Value, _mod_name: &str) {
    let name = s["name"].as_str().unwrap();
    let fields = s["fields"].as_array().unwrap();

    out.push_str(&format!("typedef struct {{\n"));
    for f in fields {
        let fname = f["name"].as_str().unwrap();
        let c_type = json_type_to_c(&f["ty"], ast);
        let comment = ownership_comment(&f["ownership"]);
        out.push_str(&format!("    {c_type:<24} {fname};{comment}\n"));
    }
    out.push_str(&format!("}} {name};\n\n"));
}

// ── Interface / method generation ───────────────────────────────────────────

fn emit_interface(out: &mut String, ast: &Value, iface: &Value, mod_name: &str) {
    let name = iface["name"].as_str().unwrap();
    let methods = iface["methods"].as_array().unwrap();
    let prefix = to_c_prefix(name);

    // Result wrapper
    emit_result_wrapper(out, ast, methods, &prefix, name, mod_name);

    // Channel handles
    out.push_str("/* ─── Channel handle (set during bootstrap) ──────────────────────────────── */\n\n");
    out.push_str(&format!(
        "extern uint16_t g_{mod_name_lower}_chan_w;\n",
        mod_name_lower = mod_name
    ));
    out.push_str(&format!(
        "extern uint16_t g_{mod_name_lower}_chan_r;\n\n",
        mod_name_lower = mod_name
    ));

    // Opcode defines
    out.push_str("/* ─── Message opcodes ───────────────────────────────────────────────────── */\n\n");
    for m in methods {
        let mname = m["name"].as_str().unwrap();
        let opcode = m["opcode"].as_u64().unwrap();
        let const_name = format!("{prefix}_OP_{}", mname.to_uppercase());
        out.push_str(&format!("#define {const_name:<32} 0x{opcode:04X}\n"));
    }
    out.push('\n');

    // Method stubs
    for m in methods {
        emit_method_stub(out, ast, m, &prefix, mod_name, name);
    }
}

// ── Result wrapper ──────────────────────────────────────────────────────────

fn emit_result_wrapper(
    out: &mut String,
    _ast: &Value,
    methods: &[Value],
    prefix: &str,
    _iface_name: &str,
    _mod_name: &str,
) {
    out.push_str("/* ─── Generated result wrapper ────────────────────────────────────────────── */\n\n");
    out.push_str("typedef struct {\n");
    out.push_str("    uint8_t ok;                   /* 1 = success, 0 = error */\n");
    out.push_str("    union {\n");

    // Collect all possible ok types from methods
    let mut seen_types: Vec<String> = Vec::new();
    for m in methods {
        let return_type = &m["return_type"];
        let kind = return_type["kind"].as_str().unwrap_or("unit");
        match kind {
            "result" => {
                if let Some(ok_type) = return_type.get("inner") {
                    let ok_kind = ok_type["kind"].as_str().unwrap_or("unit");
                    let c_type = match ok_kind {
                        "i32" => "int32_t  val_i32".into(),
                        "i64" => "int64_t  val_i64".into(),
                        "u32" => "uint32_t val_u32".into(),
                        "u64" => "uint64_t val_u64".into(),
                        "f32" => "float    val_f32".into(),
                        "f64" => "double   val_f64".into(),
                        "named" => {
                            let type_name = ok_type["name"].as_str().unwrap_or("Unknown");
                            format!("{type_name} val_{type_name_l}",
                                type_name_l = to_snake_case(type_name))
                        }
                        "array" => "uint16_t val_cap         /* MEM cap handle */".into(),
                        "unit" => continue, // no value field needed
                        _ => "uint64_t val_raw".into(),
                    };
                    if !seen_types.contains(&c_type) {
                        seen_types.push(c_type);
                    }
                }
            }
            "named" => {
                let type_name = return_type["name"].as_str().unwrap_or("Unknown");
                let c_type = format!("{type_name} val_{type_name_l}",
                    type_name_l = to_snake_case(type_name));
                if !seen_types.contains(&c_type) {
                    seen_types.push(c_type);
                }
            }
            "i32" => {
                let c = "int32_t  val_i32".into();
                if !seen_types.contains(&c) { seen_types.push(c); }
            }
            "i64" => {
                let c = "int64_t  val_i64".into();
                if !seen_types.contains(&c) { seen_types.push(c); }
            }
            "u32" => {
                let c = "uint32_t val_u32".into();
                if !seen_types.contains(&c) { seen_types.push(c); }
            }
            "f64" => {
                let c = "double   val_f64".into();
                if !seen_types.contains(&c) { seen_types.push(c); }
            }
            "unit" => continue,
            _ => {
                let c = "uint64_t val_raw".into();
                if !seen_types.contains(&c) { seen_types.push(c); }
            }
        }
    }

    // Collect error types
    let mut err_type_name: Option<String> = None;
    for m in methods {
        let return_type = &m["return_type"];
        if return_type["kind"].as_str() == Some("result") {
            if let Some(err_type) = return_type.get("inner2") {
                if err_type["kind"].as_str() == Some("named") {
                    let name = err_type["name"].as_str().unwrap_or("Error").to_string();
                    if err_type_name.is_none() {
                        err_type_name = Some(name);
                    }
                }
            }
        }
    }

    for t in &seen_types {
        out.push_str(&format!("        {t};\n"));
    }
    if let Some(ref err_name) = err_type_name {
        out.push_str(&format!("        {err_name} err;\n"));
    }

    out.push_str("    };\n");
    let type_prefix = to_c_type_prefix(prefix);
    out.push_str(&format!("}} {type_prefix}Result;\n\n"));
}

// ── Method stub generation ──────────────────────────────────────────────────

fn emit_method_stub(out: &mut String, ast: &Value, m: &Value, prefix: &str, mod_name: &str, _iface_name: &str) {
    let mname = m["name"].as_str().unwrap();
    let opcode = m["opcode"].as_u64().unwrap();
    let is_async = m["is_async"].as_bool().unwrap_or(false);
    let params = m["params"].as_array().unwrap();
    let return_type = &m["return_type"];
    let param_cap_count = m["param_cap_count"].as_u64().unwrap_or(0);

    let c_func = format!("{}_{}", mod_name, to_snake_case(mname));
    let const_name = format!("{prefix}_OP_{}", mname.to_uppercase());

    // Build C function signature
    let mut sig_params = Vec::new();
    let mut needs_arena = false;
    for p in params {
        let pname = p["name"].as_str().unwrap();
        let c_type = json_type_to_c(&p["ty"], ast);
        sig_params.push(format!("{c_type} {pname}"));
        if p["needs_cap"].as_bool().unwrap_or(false) {
            needs_arena = true;
        }
    }
    if needs_arena {
        for p in params {
            if p["needs_cap"].as_bool().unwrap_or(false) {
                let pname = p["name"].as_str().unwrap();
                sig_params.push(format!("uint16_t {pname}_cap"));
                // Array/bytes payloads carry an element count as a u32;
                // the stub needs a matching count parameter.
                let kind = p["ty"]["kind"].as_str().unwrap_or("");
                if kind == "array" || kind == "bytes" {
                    sig_params.push(format!("uint32_t {pname}_count"));
                }
            }
        }
    }

    let ret_type = if is_async {
        "void".into()
    } else {
        format!("{}Result", to_c_type_prefix(prefix))
    };

    // Doc comment
    out.push_str(&format!("/* ─── Generated stub: {mname} (opcode {opcode}) ──────────────────────── */\n\n"));

    if is_async {
        out.push_str(&format!(
            "static inline void\n{c_func}({}) {{\n",
            sig_params.join(", ")
        ));
    } else {
        out.push_str(&format!(
            "static inline {ret_type}\n{c_func}({}) {{\n",
            sig_params.join(", ")
        ));
    }

    // Build payload
    let payload_size = calculate_c_payload_size(params);
    if payload_size > 0 {
        out.push_str(&format!("    uint8_t payload[{payload_size}];\n"));
        emit_c_serialize_params(out, ast, params, "    ");
    } else {
        out.push_str("    uint8_t payload[1]; /* empty payload */\n");
    }
    out.push('\n');

    // Send request
    out.push_str("    uint32_t req_id = aerosls_next_request_id();\n");

    if param_cap_count > 0 {
        out.push_str(&format!("    aerosls_cap_desc_t caps[{param_cap_count}] = {{\n"));
        for p in params {
            if p["needs_cap"].as_bool().unwrap_or(false) {
                let pname = p["name"].as_str().unwrap();
                let ownership = p["ownership"].as_str().unwrap_or("borrowed");
                let (rights, flags) = match ownership {
                    "arena" => ("AEROSLS_CAP_PERM_R | AEROSLS_CAP_PERM_W", "AEROSLS_CAP_FLAG_ARENA"),
                    "owned" => ("AEROSLS_CAP_PERM_R | AEROSLS_CAP_PERM_W", "AEROSLS_CAP_FLAG_ARENA_OWNED"),
                    _ => ("AEROSLS_CAP_PERM_R", "AEROSLS_CAP_FLAG_BORROWED"),
                };
                let kind = p["ty"]["kind"].as_str().unwrap_or("array");
                let len_expr = if kind == "array" || kind == "bytes" {
                    // The count param is always emitted for array/bytes cap
                    // params; the multiplier is the inner element size.
                    let count_name = format!("{pname}_count");
                    let elem = c_elem_size(&p["ty"]["inner"]);
                    format!("{count_name} * sizeof({elem})")
                } else {
                    "0".into()
                };
                out.push_str(&format!(
                    "        {{ .slot = {pname}_cap, .offset = 0, .len = {len_expr}, .rights = {rights}, .flags = {flags} }},\n"
                ));
            }
        }
        out.push_str("    };\n");
    }

    if is_async {
        out.push_str(&format!(
            "    aerosls_chan_send(g_{mod_name}_chan_w, {const_name}, req_id,\n",
            mod_name = mod_name
        ));
        out.push_str("                     payload, sizeof(payload),\n");
        if param_cap_count > 0 {
            out.push_str("                     caps, sizeof(caps) / sizeof(caps[0]),\n");
        } else {
            out.push_str("                     NULL, 0,\n");
        }
        out.push_str("                     AEROSLS_CHAN_FLAG_NO_REPLY);\n");
    } else {
        out.push_str(&format!(
            "    aerosls_chan_send(g_{mod_name}_chan_w, {const_name}, req_id,\n",
            mod_name = mod_name
        ));
        out.push_str("                     payload, sizeof(payload),\n");
        if param_cap_count > 0 {
            out.push_str("                     caps, sizeof(caps) / sizeof(caps[0]),\n");
        } else {
            out.push_str("                     NULL, 0,\n");
        }
        out.push_str("                     0);\n\n");

        // Receive reply
        out.push_str("    /* ── Receive reply ── */\n");
        out.push_str(&format!("    uint8_t reply_buf[sizeof({}Result)];\n", to_c_type_prefix(prefix)));
        out.push_str("    uint16_t cap_slots[8];\n");
        out.push_str("    uint32_t reply_kind, reply_tag;\n");
        out.push_str("    size_t   reply_len;\n");
        out.push_str("    uint16_t n_caps;\n\n");

        out.push_str(&format!(
            "    aerosls_chan_recv(g_{mod_name}_chan_r,\n",
            mod_name = mod_name
        ));
        out.push_str("                     reply_buf, sizeof(reply_buf),\n");
        out.push_str("                     cap_slots, 8,\n");
        out.push_str("                     &reply_kind, &reply_tag, &reply_len, &n_caps);\n\n");

        // Deserialize reply
        out.push_str("    /* ── Deserialize reply ── */\n");
        out.push_str(&format!("    {}Result result;\n", to_c_type_prefix(prefix)));
        out.push_str("    result.ok = reply_buf[0];\n");

        let ok_type = if return_type["kind"].as_str() == Some("result") {
            return_type.get("inner").map(|t| t).unwrap_or(return_type)
        } else {
            return_type
        };
        let ok_kind = ok_type["kind"].as_str().unwrap_or("unit");

        out.push_str("    if (result.ok) {\n");
        match ok_kind {
            "i32" => {
                out.push_str("        result.val_i32 = *(int32_t *)(reply_buf + 4);\n");
            }
            "i64" => {
                out.push_str("        result.val_i64 = *(int64_t *)(reply_buf + 8);\n");
            }
            "u32" => {
                out.push_str("        result.val_u32 = *(uint32_t *)(reply_buf + 4);\n");
            }
            "f64" => {
                out.push_str("        result.val_f64 = *(double *)(reply_buf + 8);\n");
            }
            "named" => {
                let type_name = ok_type["name"].as_str().unwrap_or("Unknown");
                // Deserialize struct fields inline
                if let Some(fields) = find_struct_fields(ast, type_name) {
                    let mut inner_offset = 8;
                    for f in &fields {
                        let fname = f["name"].as_str().unwrap();
                        let fkind = f["ty"]["kind"].as_str().unwrap_or("i32");
                        let fwire = f["wire_size"].as_u64().unwrap_or(0) as usize;
                        match fkind {
                            "i32" | "u32" => {
                                out.push_str(&format!(
                                    "        result.val_{snake}.{fname} = *(uint32_t *)(reply_buf + {inner_offset});\n",
                                    snake = to_snake_case(type_name)
                                ));
                            }
                            "i64" | "u64" | "f64" => {
                                out.push_str(&format!(
                                    "        result.val_{snake}.{fname} = *(uint64_t *)(reply_buf + {inner_offset});\n",
                                    snake = to_snake_case(type_name)
                                ));
                            }
                            "named" => {
                                out.push_str(&format!(
                                    "        /* TODO: deserialize nested {fkind} at offset {inner_offset} */\n"
                                ));
                            }
                            _ => {
                                out.push_str(&format!(
                                    "        result.val_{snake}.{fname} = 0; /* TODO: deserialize {fkind} */\n",
                                    snake = to_snake_case(type_name)
                                ));
                            }
                        }
                        inner_offset += fwire;
                    }
                }
            }
            "array" => {
                out.push_str("        result.val_cap = (n_caps > 0) ? cap_slots[0] : AEROSLS_CAP_NONE;\n");
            }
            "unit" => {
                out.push_str("        /* no value to deserialize */\n");
            }
            _ => {
                out.push_str("        /* TODO: deserialize ok type */\n");
            }
        }
        out.push_str("    } else {\n");

        // Error deserialization
        if let Some(err_type) = return_type.get("inner2") {
            let err_kind = err_type["kind"].as_str().unwrap_or("unit");
            match err_kind {
                "named" => {
                    let err_name = err_type["name"].as_str().unwrap_or("Error");
                    // The wire carries the error discriminant/code as a u32 at
                    // reply_buf[4]. Assign it to the error struct's first
                    // field (CalcError.kind, LogError.code, ...) so the header
                    // works for any error struct, not just the calculator
                    // `{Err}Kind` convention.
                    let err_fields = find_struct_fields(ast, err_name);
                    let first_field = err_fields
                        .as_ref()
                        .and_then(|f| f.first())
                        .and_then(|f| f["name"].as_str())
                        .unwrap_or("kind");
                    out.push_str(&format!(
                        "        result.err.{first_field} = *(uint32_t *)(reply_buf + 4);\n"
                    ));
                    if err_fields
                        .as_ref()
                        .map(|f| f.iter().any(|f| f["name"].as_str() == Some("message")))
                        .unwrap_or(false)
                    {
                        out.push_str("        result.err.message = NULL;\n");
                    }
                }
                "string" => {
                    // String errors carry a code on the wire (reply_buf[4])
                    // but no struct member to hold a C string; leave the
                    // error code at a well-known offset for the caller.
                    out.push_str("        /* string error: code = *(uint32_t *)(reply_buf + 4) */\n");
                }
                _ => {
                    out.push_str("        /* TODO: deserialize error */\n");
                }
            }
        }
        out.push_str("    }\n\n");
        out.push_str("    return result;\n");
    }

    out.push_str("}\n\n");
}

// ── Arena helpers ───────────────────────────────────────────────────────────

fn emit_arena_helpers(out: &mut String, mod_name: &str) {
    out.push_str("/* ─── Helper: arena allocation ──────────────────────────────────────────── */\n\n");
    out.push_str(&format!(
        "/**\n * Allocate a buffer from the shared arena for the {mod_name} interface.\n * The caller owns the cap and must free it with aerosls_arena_free().\n */\n"
    ));
    out.push_str(&format!(
        "static inline uint16_t\n{mod_name}_alloc_arena_buf(size_t bytes) {{\n"
    ));
    out.push_str("    return aerosls_arena_alloc(bytes, AEROSLS_CAP_PERM_R | AEROSLS_CAP_PERM_W);\n");
    out.push_str("}\n\n");

    out.push_str(&format!(
        "/**\n * Free an arena buffer previously allocated for the {mod_name} interface.\n */\n"
    ));
    out.push_str(&format!(
        "static inline void\n{mod_name}_free_arena_buf(uint16_t cap) {{\n"
    ));
    out.push_str("    aerosls_arena_free(cap);\n");
    out.push_str("}\n\n");
}

// ── Serialization helpers ───────────────────────────────────────────────────

fn emit_c_serialize_params(out: &mut String, ast: &Value, params: &[Value], indent: &str) {
    let mut offset = 0usize;
    for p in params {
        if p["needs_cap"].as_bool().unwrap_or(false) {
            let pname = p["name"].as_str().unwrap();
            let kind = p["ty"]["kind"].as_str().unwrap_or("array");
            if kind == "array" || kind == "bytes" {
                out.push_str(&format!(
                    "{indent}*(uint32_t *)(payload + {offset}) = {pname}_count;\n"
                ));
                offset += 4;
            }
        } else {
            let pname = p["name"].as_str().unwrap();
            let wire_size = p["wire_size"].as_u64().unwrap_or(0) as usize;
            emit_c_serialize_value(out, ast, pname, &p["ty"], offset, indent);
            offset += wire_size;
        }
    }
}

fn emit_c_serialize_value(
    out: &mut String,
    ast: &Value,
    var_name: &str,
    ty: &Value,
    offset: usize,
    indent: &str,
) {
    let kind = ty["kind"].as_str().unwrap_or("i32");
    match kind {
        "i8" | "u8" | "bool" => {
            out.push_str(&format!(
                "{indent}payload[{offset}] = (uint8_t){var_name};\n"
            ));
        }
        "i16" | "u16" => {
            out.push_str(&format!(
                "{indent}*(uint16_t *)(payload + {offset}) = (uint16_t){var_name};\n"
            ));
        }
        "i32" | "u32" | "f32" => {
            out.push_str(&format!(
                "{indent}*(uint32_t *)(payload + {offset}) = *(uint32_t *)&{var_name};\n"
            ));
        }
        "i64" | "u64" | "f64" => {
            out.push_str(&format!(
                "{indent}*(uint64_t *)(payload + {offset}) = *(uint64_t *)&{var_name};\n"
            ));
        }
        "named" => {
            let type_name = ty["name"].as_str().unwrap_or("Unknown");
            if let Some(fields) = find_struct_fields(ast, type_name) {
                let mut inner_offset = offset;
                for f in &fields {
                    let fname = f["name"].as_str().unwrap();
                    let field_var = format!("{var_name}.{fname}");
                    emit_c_serialize_value(out, ast, &field_var, &f["ty"], inner_offset, indent);
                    inner_offset += get_wire_size(&f["ty"]) as usize;
                }
            }
        }
        "unit" => { /* 0 bytes */ }
        _ => {
            out.push_str(&format!(
                "{indent}/* TODO: serialize {kind} at offset {offset} */\n"
            ));
        }
    }
}

// ── Type helpers ────────────────────────────────────────────────────────────

fn json_type_to_c(ty: &Value, _ast: &Value) -> String {
    let kind = ty["kind"].as_str().unwrap_or("int32_t");
    match kind {
        "i8" => "int8_t".into(),
        "u8" => "uint8_t".into(),
        "i16" => "int16_t".into(),
        "u16" => "uint16_t".into(),
        "i32" => "int32_t".into(),
        "u32" => "uint32_t".into(),
        "i64" => "int64_t".into(),
        "u64" => "uint64_t".into(),
        "f32" => "float".into(),
        "f64" => "double".into(),
        "bool" => "uint8_t".into(),
        "string" | "bytes" => "uint16_t /* cap handle */".into(),
        "named" => ty["name"].as_str().unwrap_or("Unknown").into(),
        "array" => "uint16_t /* MEM cap handle */".into(),
        "option" => "uint16_t /* MEM cap handle or 0xFFFF */".into(),
        "result" => {
            let inner = ty.get("inner").map(|i| json_type_to_c(i, _ast)).unwrap_or_default();
            format!("{inner} /* via Result wrapper */")
        }
        "unit" => "void".into(),
        "map" => "uint16_t /* cap handle */".into(),
        _ => "uint64_t".into(),
    }
}

fn ownership_comment(ownership: &Value) -> String {
    match ownership.as_str().unwrap_or("inline") {
        "borrowed" => " /* @borrowed */".into(),
        "owned" => " /* @owned */".into(),
        "arena" => " /* @arena */".into(),
        _ => String::new(),
    }
}

fn enum_tag(enum_name: &str) -> String {
    // "CalcErrorKind" -> "ERROR", "LogLevel" -> "LEVEL", "PixelFormat" -> "FORMAT"
    // Extract the meaningful part: strip trailing "Kind" or "Type"
    let name = enum_name
        .strip_suffix("Kind")
        .or_else(|| enum_name.strip_suffix("Type"))
        .unwrap_or(enum_name);
    // "CalcError" -> "ERROR", "Log" -> "LOG", "Pixel" -> "PIXEL"
    let snake = to_snake_case(name);
    let parts: Vec<&str> = snake.split('_').collect();
    // Take the last meaningful word (the "type" part)
    let tag = if parts.len() > 1 {
        parts.last().unwrap_or(&"unknown")
    } else {
        parts.first().unwrap_or(&"unknown")
    };
    tag.to_uppercase()
}

/// Scan an array of parameter/type values for struct references, then
/// scan those structs' fields for enum types.
fn scan_struct_refs_for_enums(
    ast: &Value,
    params: &[Value],
    prefix: &str,
    map: &mut std::collections::HashMap<String, String>,
) {
    for p in params {
        let ty = if p.is_object() && p.get("ty").is_some() {
            &p["ty"]
        } else {
            p
        };
        let kind = ty["kind"].as_str().unwrap_or("");
        if kind == "named" {
            let name = ty["name"].as_str().unwrap_or("");
            if let Some(s) = find_struct(ast, name) {
                if let Some(fields) = s["fields"].as_array() {
                    for f in fields {
                        collect_enum_names(ast, &f["ty"], &mut |ename| {
                            map.entry(ename).or_insert_with(|| prefix.to_string());
                        });
                    }
                }
            }
        } else if kind == "result" {
            if let Some(inner) = ty.get("inner") {
                scan_struct_refs_for_enums(ast, &[inner.clone()], prefix, map);
            }
            if let Some(inner2) = ty.get("inner2") {
                scan_struct_refs_for_enums(ast, &[inner2.clone()], prefix, map);
            }
        } else if kind == "option" {
            if let Some(inner) = ty.get("inner") {
                scan_struct_refs_for_enums(ast, &[inner.clone()], prefix, map);
            }
        }
    }
}

/// Recursively collect enum type names referenced by a type expression.
fn collect_enum_names(ast: &Value, ty: &Value, f: &mut dyn FnMut(String)) {
    let kind = ty["kind"].as_str().unwrap_or("");
    match kind {
        "named" => {
            let name = ty["name"].as_str().unwrap_or("");
            // Check if this named type is an enum (not a struct)
            if let Some(enums) = ast["enums"].as_array() {
                if enums.iter().any(|e| e["name"].as_str() == Some(name)) {
                    f(name.to_string());
                }
            }
        }
        "result" => {
            if let Some(inner) = ty.get("inner") {
                collect_enum_names(ast, inner, f);
            }
            if let Some(inner2) = ty.get("inner2") {
                collect_enum_names(ast, inner2, f);
            }
        }
        "option" => {
            if let Some(inner) = ty.get("inner") {
                collect_enum_names(ast, inner, f);
            }
        }
        _ => {}
    }
}

fn to_c_name(ns: &str) -> String {
    // "aerosls.calculator" -> "calculator"
    ns.split('.').last().unwrap_or(ns).replace('-', "_")
}

fn to_c_prefix(iface_name: &str) -> String {
    // "CalculatorService" -> "CALC" (first word, uppercased)
    // "LoggingService" -> "LOG"
    // "ImageProcessingService" -> "IMAG"
    let snake = to_snake_case(iface_name);
    let first_word = snake.split('_').next().unwrap_or(&snake);
    let prefix: String = first_word.chars().take(4).map(|c| c.to_ascii_uppercase()).collect();
    prefix
}

/// Capitalized prefix for type names: "CALC" -> "Calc", "LOG" -> "Log"
fn to_c_type_prefix(prefix: &str) -> String {
    let mut chars = prefix.chars();
    match chars.next() {
        Some(first) => {
            let mut s = first.to_uppercase().to_string();
            s.extend(chars.map(|c| c.to_ascii_lowercase()));
            s
        }
        None => String::new(),
    }
}

fn to_c_name_from_prefix(prefix: &str) -> String {
    // "CALC" -> "calculator" (reverse of to_c_prefix)
    prefix.to_lowercase()
}

fn to_snake_case(s: &str) -> String {
    let mut result = String::with_capacity(s.len() + 4);
    for (i, ch) in s.chars().enumerate() {
        if ch == '_' {
            result.push('_');
        } else if ch.is_uppercase() {
            if i > 0 {
                let prev = s.as_bytes()[i - 1] as char;
                if prev != '_' && prev.is_lowercase() {
                    result.push('_');
                }
            }
            result.push(ch.to_ascii_lowercase());
        } else {
            result.push(ch);
        }
    }
    result
}

fn find_struct<'a>(ast: &'a Value, name: &str) -> Option<&'a Value> {
    ast["structs"].as_array()?.iter().find(|s| s["name"].as_str() == Some(name))
}

fn find_struct_fields<'a>(ast: &'a Value, name: &str) -> Option<Vec<&'a Value>> {
    let s = ast["structs"]
        .as_array()?
        .iter()
        .find(|s| s["name"].as_str() == Some(name))?;
    Some(s["fields"].as_array()?.iter().collect())
}

fn get_wire_size(ty: &Value) -> u64 {
    let kind = ty["kind"].as_str().unwrap_or("i32");
    match kind {
        "i8" | "u8" | "bool" => 1,
        "i16" | "u16" => 2,
        "i32" | "u32" | "f32" => 4,
        "i64" | "u64" | "f64" => 8,
        "string" | "bytes" | "array" | "map" => 8,
        _ => 8,
    }
}

/// C element type for the inner type of an array/bytes cap param.
fn c_elem_size(ty: &Value) -> &'static str {
    let kind = ty["kind"].as_str().unwrap_or("u8");
    match kind {
        "i8" | "u8" | "bool" => "uint8_t",
        "i16" | "u16" => "uint16_t",
        "i32" | "u32" => "uint32_t",
        "i64" | "u64" => "uint64_t",
        "f32" => "float",
        "f64" => "double",
        _ => "uint8_t",
    }
}

fn calculate_c_payload_size(params: &[Value]) -> usize {
    let mut size = 0usize;
    for p in params {
        if p["needs_cap"].as_bool().unwrap_or(false) {
            let kind = p["ty"]["kind"].as_str().unwrap_or("array");
            if kind == "array" || kind == "bytes" {
                size += 4; // count as u32
            }
        } else {
            size += p["wire_size"].as_u64().unwrap_or(0) as usize;
        }
    }
    size
}

// ── Tests ───────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn emit_calculator_c() {
        let src = include_str!("../../../idl/calculator.aeroidl");
        let doc = crate::parser::parse(src).expect("parse should succeed");
        let tc = crate::tycheck::type_check(&doc);
        let ast = crate::emit::emit_value(&doc, &tc);
        let c_code = emit_c(&ast);

        assert!(c_code.contains("#ifndef AEROSLS_CALCULATOR_H"));
        assert!(c_code.contains("#define AEROSLS_CALCULATOR_H"));
        assert!(c_code.contains("typedef enum {"));
        assert!(c_code.contains("CALC_ERROR_DIVISION_BY_ZERO = 1"));
        assert!(c_code.contains("typedef struct {"));
        assert!(c_code.contains("CalcErrorKind") && c_code.contains("kind;"));
        assert!(c_code.contains("double") && c_code.contains(" x;"));
        assert!(c_code.contains("double") && c_code.contains(" y;"));
        assert!(c_code.contains("typedef struct {"));
        assert!(c_code.contains("CalcResult"));
        assert!(c_code.contains("extern uint16_t g_calculator_chan_w;"));
        assert!(c_code.contains("extern uint16_t g_calculator_chan_r;"));
        assert!(c_code.contains("#define CALC_OP_ADD"));
        assert!(c_code.contains("static inline CalcResult"));
        assert!(c_code.contains("calculator_add("));
        assert!(c_code.contains("calculator_div("));
        assert!(c_code.contains("calculator_dot("));
        assert!(c_code.contains("calculator_sqrt_batch("));
        assert!(c_code.contains("calculator_heavy_reduce("));
        assert!(c_code.contains("aerosls_chan_send("));
        assert!(c_code.contains("aerosls_chan_recv("));
        assert!(c_code.contains("calculator_alloc_arena_buf("));
        assert!(c_code.contains("calculator_free_arena_buf("));
        assert!(c_code.contains("#ifdef __cplusplus"));
        assert!(c_code.contains("#endif /* AEROSLS_CALCULATOR_H */"));
    }

    #[test]
    fn emit_logging_c() {
        let src = include_str!("../../../idl/logging.aeroidl");
        let doc = crate::parser::parse(src).expect("parse should succeed");
        let tc = crate::tycheck::type_check(&doc);
        let ast = crate::emit::emit_value(&doc, &tc);
        let c_code = emit_c(&ast);

        assert!(c_code.contains("#ifndef AEROSLS_LOGGING_H"));
        assert!(c_code.contains("LOGG_LEVEL_TRACE = 0"));
        assert!(c_code.contains("typedef struct {"));
        assert!(c_code.contains("timestamp_ms;"));
        assert!(c_code.contains("g_logging_chan_w;"));
        assert!(c_code.contains("LOGG_OP_EMIT"));
        assert!(c_code.contains("logging_emit("));
        assert!(c_code.contains("logging_flush("));
        assert!(c_code.contains("logging_set_level("));
    }

    #[test]
    fn emit_imageproc_c() {
        let src = include_str!("../../../idl/imageproc.aeroidl");
        let doc = crate::parser::parse(src).expect("parse should succeed");
        let tc = crate::tycheck::type_check(&doc);
        let ast = crate::emit::emit_value(&doc, &tc);
        let c_code = emit_c(&ast);

        assert!(c_code.contains("#ifndef AEROSLS_IMAGEPROC_H"));
        assert!(c_code.contains("IMAG_FORMAT_RGB8 = 0"));
        assert!(c_code.contains("width;"));
        assert!(c_code.contains("/* cap handle */ data;"));
        assert!(c_code.contains("g_imageproc_chan_w;"));
        assert!(c_code.contains("#define IMAG_OP_BLUR"));
        assert!(c_code.contains("imageproc_blur("));
        assert!(c_code.contains("imageproc_resize_inplace("));
    }

    #[test]
    fn c_header_guard_format() {
        let src = include_str!("../../../idl/calculator.aeroidl");
        let doc = crate::parser::parse(src).expect("parse should succeed");
        let tc = crate::tycheck::type_check(&doc);
        let ast = crate::emit::emit_value(&doc, &tc);
        let c_code = emit_c(&ast);

        // Must start with /** comment
        assert!(c_code.starts_with("/**"));
        // Must end with #endif
        assert!(c_code.trim_end().ends_with("*/"));
        // Must have matching include guard
        assert!(c_code.contains("#ifndef AEROSLS_CALCULATOR_H"));
        assert!(c_code.contains("#endif /* AEROSLS_CALCULATOR_H */"));
    }

    #[test]
    fn c_prefix_conversion() {
        assert_eq!(to_c_prefix("CalculatorService"), "CALC");
        assert_eq!(to_c_prefix("LoggingService"), "LOGG");
        assert_eq!(to_c_prefix("ImageProcessingService"), "IMAG");
    }
}
