#!/usr/bin/env python3
"""bundle_webapp.py — Generate kernel/webapp_bundle.c from slsos-sim/dist/

Usage:
    python3 tools/bundle_webapp.py <dist-dir> > kernel/webapp_bundle.c
  or via Makefile:
    make bundle

The generated file embeds every file under <dist-dir> as a const uint8_t[]
in .rodata and produces a bundle_find() lookup function used by the kernel's
HTTP server to serve the Navigator SPA directly from the running OS.
"""
import os, sys

MIME_MAP = {
    '.html':  'text/html; charset=utf-8',
    '.js':    'application/javascript',
    '.mjs':   'application/javascript',
    '.css':   'text/css',
    '.ico':   'image/x-icon',
    '.png':   'image/png',
    '.jpg':   'image/jpeg',
    '.jpeg':  'image/jpeg',
    '.svg':   'image/svg+xml',
    '.woff':  'font/woff',
    '.woff2': 'font/woff2',
    '.ttf':   'font/ttf',
    '.json':  'application/json',
    '.map':   'application/json',
    '.txt':   'text/plain',
}

def c_ident(path):
    """Turn a URL path like /assets/main-abc.js into _bundle_assets_main_abc_js"""
    s = path.strip('/')
    result = []
    for ch in s:
        if ch.isalnum():
            result.append(ch)
        else:
            result.append('_')
    return '_bundle_' + ''.join(result) if result else '_bundle_root'

def collect_files(dist_dir):
    """Walk dist_dir and return list of (url_path, abs_path, mime) tuples."""
    files = []
    for dirpath, _dirs, filenames in os.walk(dist_dir):
        for fname in sorted(filenames):
            abspath = os.path.join(dirpath, fname)
            relpath = os.path.relpath(abspath, dist_dir)
            # Normalise to forward slashes for URL
            url_path = '/' + relpath.replace(os.sep, '/')
            ext = os.path.splitext(fname)[1].lower()
            mime = MIME_MAP.get(ext, 'application/octet-stream')
            files.append((url_path, abspath, mime))
    return files

def emit_array(ident, data):
    """Emit:  static const uint8_t <ident>[] = { ... };"""
    print(f'static const uint8_t {ident}[] = {{')
    cols = 0
    for i, b in enumerate(data):
        if cols == 0:
            print('    ', end='')
        print(f'0x{b:02x}', end='')
        cols += 1
        if i < len(data) - 1:
            print(',', end='')
            if cols >= 16:
                print()
                cols = 0
            else:
                print(' ', end='')
    print()
    print('};')

def main():
    if len(sys.argv) < 2:
        print(f'Usage: {sys.argv[0]} <dist-dir>', file=sys.stderr)
        sys.exit(1)

    dist_dir = sys.argv[1]
    if not os.path.isdir(dist_dir):
        print(f'Error: {dist_dir} is not a directory', file=sys.stderr)
        sys.exit(1)

    files = collect_files(dist_dir)

    print('// ── Auto-generated by tools/bundle_webapp.py ── do not edit ──────────────')
    print('// Regenerate with:  make bundle')
    print('//')
    print(f'// Source: {os.path.abspath(dist_dir)}')
    print(f'// Files:  {len(files)}')
    total = sum(os.path.getsize(a) for _, a, _ in files)
    print(f'// Total:  {total:,} bytes ({total // 1024} KiB)')
    print()
    print('#include <stdint.h>')
    print('#include "bundle.h"')
    print()

    # Emit one array per file
    idents = []
    for url_path, abspath, mime in files:
        ident = c_ident(url_path)
        # Deduplicate idents (can happen for index.html mapped to both / and /index.html)
        # We'll reuse the same ident for duplicate content
        with open(abspath, 'rb') as f:
            data = f.read()
        emit_array(ident, data)
        print()
        idents.append((url_path, ident, mime, len(data)))

    # index.html also maps to / and /index.html
    index_entry = next(((u, i, m, l) for u, i, m, l in idents if u == '/index.html'), None)

    print('static const struct BundleAsset _bundle_table[] = {')
    if index_entry:
        u, i, m, l = index_entry
        print(f'    {{ "/",           "{m}", {i}, {l}U }},')
    for url_path, ident, mime, length in idents:
        print(f'    {{ "{url_path}", "{mime}", {ident}, {length}U }},')
    print('    { 0, 0, 0, 0 }')
    print('};')
    print()
    print('const struct BundleAsset* bundle_find(const char* path) {')
    print('    for (int i = 0; _bundle_table[i].path; i++)')
    print('        if (__builtin_strcmp(_bundle_table[i].path, path) == 0)')
    print('            return &_bundle_table[i];')
    print('    return 0;')
    print('}')

if __name__ == '__main__':
    main()
