
// ═══════════════════════════════════════════════════════════════════════════
// Common types — shared by all generated AeroIDL modules
// ═══════════════════════════════════════════════════════════════════════════

/// Error type for AeroIDL cross-sidecar calls.
#[derive(Clone, Debug)]
pub struct AEROIDL_ERROR {
    pub code: u32,
    pub message: alloc::string::String,
}

impl core::fmt::Display for AEROIDL_ERROR {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        write!(f, "AeroIDL error {}: {}", self.code, self.message)
    }
}

/// Result type for AeroIDL cross-sidecar calls.
pub type AeroidlResult<T> = Result<T, AEROIDL_ERROR>;

/// A slice referencing arena-allocated data via a MEM cap handle.
/// The cap handle points into the shared arena visible to both sidecars.
#[derive(Clone, Copy, Debug)]
pub struct ArenaSlice<T> {
    pub cap: u16,
    pub len: u32,
    _marker: core::marker::PhantomData<T>,
}

impl<T> ArenaSlice<T> {
    pub fn new(cap: u16, len: u32) -> Self {
        Self {
            cap,
            len,
            _marker: core::marker::PhantomData,
        }
    }

    /// Get the cap handle.
    pub fn cap_handle(self) -> u16 {
        self.cap
    }

    /// Get the element count (for fixed-size T).
    pub fn len(self) -> u32 {
        self.len
    }
}

/// Capability argument descriptor (16 bytes, matching kernel cap.h layout).
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct CapDescriptor {
    pub slot: u32,
    pub offset: u32,
    pub len: u32,
    pub rights: u8,
    pub flags: u8,
    pub pad: u16,
}

// Permission constants (matching cap.h)
pub const CAP_PERM_R: u8 = 0x01;
pub const CAP_PERM_W: u8 = 0x02;

// Capability ownership flags (matching user/libaerocap/aerosls_cap.h
// AEROSLS_CAP_FLAG_*): BORROWED = caller retains ownership, ARENA = shared
// arena slot, ARENA_OWNED = ownership transfers to the callee on send.
pub const CAP_FLAG_BORROWED: u8 = 0x00;
pub const CAP_FLAG_ARENA: u8 = 0x01;
pub const CAP_FLAG_ARENA_OWNED: u8 = 0x02;

// Channel flag constants — kernel message flags (kernel/cap.h ChanMsg.flags,
// bit0 = NO_REPLY). MUST match user/libaerocap/aerosls_cap.h's
// AEROSLS_CHAN_FLAG_NO_REPLY and the runtime's req::CHAN_FLAG_NO_REPLY.
pub const CHAN_FLAG_NO_REPLY: u16 = 0x0001;

// Capability sentinel
pub const CAP_NONE: u16 = 0xFFFF;

// ═══════════════════════════════════════════════════════════════════════════
// Sidecar runtime FFI — provided by the sidecar SDK (linked separately)
// ═══════════════════════════════════════════════════════════════════════════

extern "C" {
    /// Send a message on a channel with optional capability descriptors.
    pub fn chan_send(
        chan_w: u16,
        opcode: u16,
        payload: *const u8,
        payload_len: u32,
        caps: *const CapDescriptor,
        n_caps: u32,
        flags: u16,
    ) -> i32;

    /// Receive a message from a channel.
    pub fn chan_recv(
        chan_r: u16,
        buf: *mut u8,
        buf_len: u32,
        cap_slots: *mut u16,
        n_slots: *mut u16,
    ) -> i32;

    /// Allocate a buffer from the shared arena.
    pub fn arena_alloc(size: u32, perm: u8) -> u16;

    /// Free an arena buffer.
    pub fn arena_free(cap: u16);

    /// Get the raw pointer for an arena buffer (for zero-copy access).
    pub fn arena_mem(cap: u16) -> *mut u8;

    /// Get the next request ID (monotonically incrementing).
    pub fn next_request_id() -> u32;
}


// Auto-generated by aeroidl-cc v0.1 — aerosls.calculator
// AeroIDL version: aeroidl/1.0
//
// This module provides Rust FFI stubs for cross-sidecar calls.
// The sidecar runtime provides:
//   aerosls::chan_send(), aerosls::chan_recv(),
//   aerosls::arena_alloc(), aerosls::arena_free()
//
// Generated from the typed AST — do not edit manually.

use core::mem;

/// CalcErrorKind — AeroIDL enum (wire size: 4 bytes)
#[repr(u32)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum CalcErrorKind {
    DIVISION_BY_ZERO = 1,
    OVERFLOW = 2,
    UNDERFLOW = 3,
    INVALID_INPUT = 4,
    INTERNAL = 5,
}

impl CalcErrorKind {
    /// Convert from raw discriminant value.
    pub fn from_raw(v: u32) -> Option<Self> {
        match v {
            1 => Some(CalcErrorKind::DIVISION_BY_ZERO),
            2 => Some(CalcErrorKind::OVERFLOW),
            3 => Some(CalcErrorKind::UNDERFLOW),
            4 => Some(CalcErrorKind::INVALID_INPUT),
            5 => Some(CalcErrorKind::INTERNAL),
            _ => None,
        }
    }

    /// Convert to raw discriminant value.
    pub fn to_raw(self) -> u32 {
        self as u32
    }
}

/// CalcError — AeroIDL struct (wire size: 12 bytes
/// )
#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct CalcError {
    pub kind: CalcErrorKind,
    pub message: u16 /* cap handle */, /* @borrowed */
}

impl CalcError {
    pub const WIRE_SIZE: usize = 12;
}

/// Vec2 — AeroIDL struct (wire size: 16 bytes
/// )
#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct Vec2 {
    pub x: f64,
    pub y: f64,
}

impl Vec2 {
    pub const WIRE_SIZE: usize = 16;
}

/// MatrixData — AeroIDL struct (wire size: 16 bytes
/// )
#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct MatrixData {
    pub rows: u32,
    pub cols: u32,
    pub elements: ArenaSlice<f64>, /* @arena */
}

impl MatrixData {
    pub const WIRE_SIZE: usize = 16;
}

/// CalculatorService — AeroIDL interface
pub mod calculator_service {
    use super::*;

    /// Message opcodes for channel send/recv.
    pub const OP_ADD: u16 = 1;
    pub const OP_DIV: u16 = 2;
    pub const OP_DOT: u16 = 3;
    pub const OP_MATMUL_VEC: u16 = 4;
    pub const OP_SQRT_BATCH: u16 = 5;
    pub const OP_HEAVY_REDUCE: u16 = 6;
    pub const OP_REVERSE: u16 = 7;

    /// Lisp-side compute time (nanoseconds) for the last sqrt_batch reply,
    /// carried in reply bytes 8..16 as u64 microseconds. Lets the sidecar
    /// split the SQRT bench into compute vs transport.
    pub static mut LAST_SQRT_COMPUTE_NS: u64 = 0;

    /// Channel write endpoint (CHAN_W) to the remote sidecar.
    /// Set during bootstrap by the sidecar runtime.
    pub static mut CHAN_W: u16 = 0xFFFF; /* CAP_NONE */

    /// Channel read endpoint (CHAN_R) from the remote sidecar.
    pub static mut CHAN_R: u16 = 0xFFFF; /* CAP_NONE */

    /// `add` — opcode 1
    ///
    /// # Wire format
    ///   SEND_CAP { opcode=1, payload=[...], caps=[...] }
    ///   RECV_CAP { payload=[AeroidlResult], caps=[...] }

    pub fn add(a: i32, b: i32) -> AeroidlResult<i32> {
        // ── Step 1: build request payload ──
        let mut payload = [0u8; 8];
        payload[0..0+4].copy_from_slice(&(a as u32).to_le_bytes());
        payload[4..4+4].copy_from_slice(&(b as u32).to_le_bytes());

        // ── Step 2: send request ──
        let flags: u16 = 0;
        unsafe {
            let _rc = chan_send(
                CHAN_W,
                OP_ADD,
                payload.as_ptr(),
                payload.len() as u32,
                core::ptr::null(),
                0,
                flags,
            );
            if _rc != 0 {
                return Err(AEROIDL_ERROR { code: _rc as u32, message: alloc::string::String::from("chan_send failed") });
            }
        }

        // ── Step 3: receive reply ──
        let mut reply_buf = [0u8; 32];
        let mut cap_slots = [0u16; 8];
        let mut n_caps: u16 = 0;
        unsafe {
            let _rc = chan_recv(
                CHAN_R,
                reply_buf.as_mut_ptr(),
                reply_buf.len() as u32,
                cap_slots.as_mut_ptr(),
                &mut n_caps as *mut u16,
            );
            if _rc != 0 {
                return Err(AEROIDL_ERROR { code: _rc as u32, message: alloc::string::String::from("chan_recv failed") });
            }
        }

        // ── Step 4: deserialize reply ──
        let ok_byte = reply_buf[0];
        if ok_byte == 1 {
            let val = i32::from_le_bytes(reply_buf[4..8].try_into().unwrap());
            Ok(val)
        } else {
            let code = u32::from_le_bytes(reply_buf[4..8].try_into().unwrap());
            Err(AEROIDL_ERROR { code, message: alloc::string::String::new() })
        }
    }

    /// `div` — opcode 2
    ///
    /// # Wire format
    ///   SEND_CAP { opcode=2, payload=[...], caps=[...] }
    ///   RECV_CAP { payload=[AeroidlResult], caps=[...] }

    pub fn div(a: i64, b: i64) -> AeroidlResult<i64> {
        // ── Step 1: build request payload ──
        let mut payload = [0u8; 16];
        payload[0..0+8].copy_from_slice(&(a as u64).to_le_bytes());
        payload[8..8+8].copy_from_slice(&(b as u64).to_le_bytes());

        // ── Step 2: send request ──
        let flags: u16 = 0;
        unsafe {
            let _rc = chan_send(
                CHAN_W,
                OP_DIV,
                payload.as_ptr(),
                payload.len() as u32,
                core::ptr::null(),
                0,
                flags,
            );
            if _rc != 0 {
                return Err(AEROIDL_ERROR { code: _rc as u32, message: alloc::string::String::from("chan_send failed") });
            }
        }

        // ── Step 3: receive reply ──
        let mut reply_buf = [0u8; 32];
        let mut cap_slots = [0u16; 8];
        let mut n_caps: u16 = 0;
        unsafe {
            let _rc = chan_recv(
                CHAN_R,
                reply_buf.as_mut_ptr(),
                reply_buf.len() as u32,
                cap_slots.as_mut_ptr(),
                &mut n_caps as *mut u16,
            );
            if _rc != 0 {
                return Err(AEROIDL_ERROR { code: _rc as u32, message: alloc::string::String::from("chan_recv failed") });
            }
        }

        // ── Step 4: deserialize reply ──
        let ok_byte = reply_buf[0];
        if ok_byte == 1 {
            let val = i64::from_le_bytes(reply_buf[8..16].try_into().unwrap());
            Ok(val)
        } else {
            let code = u32::from_le_bytes(reply_buf[4..8].try_into().unwrap());
            Err(AEROIDL_ERROR { code, message: alloc::string::String::new() })
        }
    }

    /// `dot` — opcode 3
    ///
    /// # Wire format
    ///   SEND_CAP { opcode=3, payload=[...], caps=[...] }
    ///   RECV_CAP { payload=[AeroidlResult], caps=[...] }

    pub fn dot(a: Vec2, b: Vec2) -> AeroidlResult<f64> {
        // ── Step 1: build request payload ──
        let mut payload = [0u8; 32];
        payload[0..0+8].copy_from_slice(&(a.x as u64).to_le_bytes());
        payload[8..8+8].copy_from_slice(&(a.y as u64).to_le_bytes());
        payload[16..16+8].copy_from_slice(&(b.x as u64).to_le_bytes());
        payload[24..24+8].copy_from_slice(&(b.y as u64).to_le_bytes());

        // ── Step 2: send request ──
        let flags: u16 = 0;
        unsafe {
            let _rc = chan_send(
                CHAN_W,
                OP_DOT,
                payload.as_ptr(),
                payload.len() as u32,
                core::ptr::null(),
                0,
                flags,
            );
            if _rc != 0 {
                return Err(AEROIDL_ERROR { code: _rc as u32, message: alloc::string::String::from("chan_send failed") });
            }
        }

        // ── Step 3: receive reply ──
        let mut reply_buf = [0u8; 32];
        let mut cap_slots = [0u16; 8];
        let mut n_caps: u16 = 0;
        unsafe {
            let _rc = chan_recv(
                CHAN_R,
                reply_buf.as_mut_ptr(),
                reply_buf.len() as u32,
                cap_slots.as_mut_ptr(),
                &mut n_caps as *mut u16,
            );
            if _rc != 0 {
                return Err(AEROIDL_ERROR { code: _rc as u32, message: alloc::string::String::from("chan_recv failed") });
            }
        }

        // ── Step 4: deserialize reply ──
        let ok_byte = reply_buf[0];
        if ok_byte == 1 {
            let val = f64::from_le_bytes(reply_buf[8..16].try_into().unwrap());
            Ok(val)
        } else {
            let code = u32::from_le_bytes(reply_buf[4..8].try_into().unwrap());
            Err(AEROIDL_ERROR { code, message: alloc::string::String::new() })
        }
    }

    /// `matmul_vec` — opcode 4
    ///
    /// # Wire format
    ///   SEND_CAP { opcode=4, payload=[...], caps=[...] }
    ///   RECV_CAP { payload=[AeroidlResult], caps=[...] }

    pub fn matmul_vec(m: MatrixData, v: Vec2) -> AeroidlResult<Vec2> {
        // ── Step 1: build request payload ──
        let mut payload = [0u8; 32];
        payload[0..0+4].copy_from_slice(&(m.rows as u32).to_le_bytes());
        payload[4..4+4].copy_from_slice(&(m.cols as u32).to_le_bytes());
        // TODO: serialize array at offset 8
        payload[16..16+8].copy_from_slice(&(v.x as u64).to_le_bytes());
        payload[24..24+8].copy_from_slice(&(v.y as u64).to_le_bytes());

        // ── Step 2: send request ──
        let flags: u16 = 0;
        unsafe {
            let _rc = chan_send(
                CHAN_W,
                OP_MATMUL_VEC,
                payload.as_ptr(),
                payload.len() as u32,
                core::ptr::null(),
                0,
                flags,
            );
            if _rc != 0 {
                return Err(AEROIDL_ERROR { code: _rc as u32, message: alloc::string::String::from("chan_send failed") });
            }
        }

        // ── Step 3: receive reply ──
        let mut reply_buf = [0u8; 32];
        let mut cap_slots = [0u16; 8];
        let mut n_caps: u16 = 0;
        unsafe {
            let _rc = chan_recv(
                CHAN_R,
                reply_buf.as_mut_ptr(),
                reply_buf.len() as u32,
                cap_slots.as_mut_ptr(),
                &mut n_caps as *mut u16,
            );
            if _rc != 0 {
                return Err(AEROIDL_ERROR { code: _rc as u32, message: alloc::string::String::from("chan_recv failed") });
            }
        }

        // ── Step 4: deserialize reply ──
        let ok_byte = reply_buf[0];
        if ok_byte == 1 {
            // Deserialize Vec2 from reply payload
            let x = u64::from_le_bytes(reply_buf[8..8+8].try_into().unwrap());
            let y = u64::from_le_bytes(reply_buf[16..16+8].try_into().unwrap());
            Ok(Vec2 { x: x as _, y: y as _ })
        } else {
            let code = u32::from_le_bytes(reply_buf[4..8].try_into().unwrap());
            Err(AEROIDL_ERROR { code, message: alloc::string::String::new() })
        }
    }

    /// `sqrt_batch` — opcode 5
    ///
    /// # Wire format
    ///   SEND_CAP { opcode=5, payload=[...], caps=[...] }
    ///   RECV_CAP { payload=[AeroidlResult], caps=[...] }

    pub fn sqrt_batch(input: ArenaSlice<f64>, input_cap: u16, input_len: u32) -> AeroidlResult<ArenaSlice<f64>> {
        // ── Step 1: build request payload ──
        let mut payload = [0u8; 4];
        payload[0..0+4].copy_from_slice(&input_len.to_le_bytes());

        // ── Step 2: send request ──
        let flags: u16 = 0;
        let cap_descs = [
            CapDescriptor { slot: input_cap as u32, offset: 0, len: input_len, rights: CAP_PERM_R, flags: CAP_FLAG_BORROWED, pad: 0 },
        ];
        let n_caps_send: u32 = cap_descs.len() as u32;
        unsafe {
            let _rc = chan_send(
                CHAN_W,
                OP_SQRT_BATCH,
                payload.as_ptr(),
                payload.len() as u32,
                cap_descs.as_ptr(),
                n_caps_send,
                flags,
            );
            if _rc != 0 {
                return Err(AEROIDL_ERROR { code: _rc as u32, message: alloc::string::String::from("chan_send failed") });
            }
        }

        // ── Step 3: receive reply ──
        let mut reply_buf = [0u8; 32];
        let mut cap_slots = [0u16; 8];
        let mut n_caps: u16 = 0;
        unsafe {
            let _rc = chan_recv(
                CHAN_R,
                reply_buf.as_mut_ptr(),
                reply_buf.len() as u32,
                cap_slots.as_mut_ptr(),
                &mut n_caps as *mut u16,
            );
            if _rc != 0 {
                return Err(AEROIDL_ERROR { code: _rc as u32, message: alloc::string::String::from("chan_recv failed") });
            }
        }

        // ── Step 4: deserialize reply ──
        let ok_byte = reply_buf[0];
        // Lisp-side compute split: u64 microseconds at bytes 8..16 -> ns.
        unsafe {
            LAST_SQRT_COMPUTE_NS = u64::from_le_bytes(reply_buf[8..16].try_into().unwrap_or([0; 8])) * 1000;
        }
        if ok_byte == 1 {
            // Arena cap handle is in cap_slots[0], count in reply_buf[4..8]
            let count = u32::from_le_bytes(reply_buf[4..8].try_into().unwrap());
            Ok(ArenaSlice::new(cap_slots[0], count))
        } else {
            let code = u32::from_le_bytes(reply_buf[4..8].try_into().unwrap());
            Err(AEROIDL_ERROR { code, message: alloc::string::String::new() })
        }
    }

    /// `heavy_reduce` — opcode 6
    ///
    /// Async call: sends with NO_REPLY flag.
    /// The result is delivered later on a dedicated result channel.
    ///
    /// # Wire format
    ///   SEND_CAP { opcode=6, payload=[...], caps=[...] }

    pub fn heavy_reduce(input: ArenaSlice<f64>, input_cap: u16, input_len: u32) -> Result<(), AEROIDL_ERROR> {
        // ── Step 1: build request payload ──
        let mut payload = [0u8; 4];
        payload[0..0+4].copy_from_slice(&input_len.to_le_bytes());

        // ── Step 2: send request ──
        let flags = CHAN_FLAG_NO_REPLY;
        let cap_descs = [
            CapDescriptor { slot: input_cap as u32, offset: 0, len: input_len, rights: CAP_PERM_R | CAP_PERM_W, flags: CAP_FLAG_ARENA, pad: 0 },
        ];
        let n_caps_send: u32 = cap_descs.len() as u32;
        unsafe {
            let _rc = chan_send(
                CHAN_W,
                OP_HEAVY_REDUCE,
                payload.as_ptr(),
                payload.len() as u32,
                cap_descs.as_ptr(),
                n_caps_send,
                flags,
            );
            if _rc != 0 {
                return Err(AEROIDL_ERROR { code: _rc as u32, message: alloc::string::String::from("chan_send failed") });
            }
        }
        Ok(())
    }

    /// `reverse` — opcode 7
    ///
    /// # Wire format
    ///   SEND_CAP { opcode=7, payload=[text_len u32], caps=[MEM input @borrowed] }
    ///   RECV_CAP { payload=[AeroidlResult], caps=[MEM output @arena] }
    /// The reply string is an arena cap (ArenaSlice<u8>); the Lisp side
    /// reverses the input bytes into a fresh arena buffer and transfers the
    /// cap back.

    pub fn reverse(text_cap: u16, text_len: u32) -> AeroidlResult<ArenaSlice<u8>> {
        // ── Step 1: build request payload ──
        let mut payload = [0u8; 4];
        payload[0..0+4].copy_from_slice(&text_len.to_le_bytes());

        // ── Step 2: send request ──
        let flags: u16 = 0;
        let cap_descs = [
            CapDescriptor { slot: text_cap as u32, offset: 0, len: text_len, rights: CAP_PERM_R, flags: CAP_FLAG_BORROWED, pad: 0 },
        ];
        let n_caps_send: u32 = cap_descs.len() as u32;
        unsafe {
            let _rc = chan_send(
                CHAN_W,
                OP_REVERSE,
                payload.as_ptr(),
                payload.len() as u32,
                cap_descs.as_ptr(),
                n_caps_send,
                flags,
            );
            if _rc != 0 {
                return Err(AEROIDL_ERROR { code: _rc as u32, message: alloc::string::String::from("chan_send failed") });
            }
        }

        // ── Step 3: receive reply ──
        let mut reply_buf = [0u8; 32];
        let mut cap_slots = [0u16; 8];
        let mut n_caps: u16 = 0;
        unsafe {
            let _rc = chan_recv(
                CHAN_R,
                reply_buf.as_mut_ptr(),
                reply_buf.len() as u32,
                cap_slots.as_mut_ptr(),
                &mut n_caps as *mut u16,
            );
            if _rc != 0 {
                return Err(AEROIDL_ERROR { code: _rc as u32, message: alloc::string::String::from("chan_recv failed") });
            }
        }

        // ── Step 4: deserialize reply ──
        let ok_byte = reply_buf[0];
        if ok_byte == 1 {
            // Arena cap handle is in cap_slots[0], byte count in reply_buf[4..8]
            let len = u32::from_le_bytes(reply_buf[4..8].try_into().unwrap());
            Ok(ArenaSlice::new(cap_slots[0], len))
        } else {
            let code = u32::from_le_bytes(reply_buf[4..8].try_into().unwrap());
            Err(AEROIDL_ERROR { code, message: alloc::string::String::new() })
        }
    }

}

